import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const SEEN=['BTCUSDT','ETHUSDT','SOLUSDT','ZECUSDT','XRPUSDT','ENSOUSDT','UNIUSDT','ARBUSDT','BNBUSDT','ENAUSDT','UUSDT','SNDKBUSDT','NEARUSDT','DOGEUSDT','TRXUSDT','LINKUSDT','SUIUSDT','DASHUSDT','PUMPUSDT','0GUSDT','TRUMPUSDT','PEPEUSDT','CRCLBUSDT','ADAUSDT','HEMIUSDT','CRVUSDT','OPUSDT','WLDUSDT','SPCXBUSDT','TUTUSDT','GRAMUSDT','AAVEUSDT','ONGUSDT','LTCUSDT','AVAXUSDT','TAOUSDT','XPLUSDT','BMTUSDT','MSTRBUSDT','SCUSDT','ACEUSDT','ONDOUSDT','PROMUSDT','INJUSDT','ZROUSDT','SNXXBUSDT','QQQBUSDT','FETUSDT','APTUSDT','FFUSDT','FILUSDT','ASTERUSDT','POLUSDT','BCHUSDT','BONKUSDT','DOTUSDT','SOXLBUSDT','ACTUSDT','MORPHOUSDT','PENGUUSDT','MUBUSDT','CHIPUSDT','TWTUSDT','ZENUSDT','SKYUSDT','DOGSUSDT','CAKEUSDT','ARUSDT','BICOUSDT','JSTUSDT','SKHYBUSDT','ETHFIUSDT','ATMUSDT','NOTUSDT','WLFIUSDT','VIRTUALUSDT','ZKCUSDT','ZKUSDT','GIGGLEUSDT','DEXEUSDT'];
const HOLD=['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT'];
const EXCL=new Set([...SEEN,...HOLD]);
const BAD=new Set(['USDC','FDUSD','TUSD','USDP','DAI','EUR','AEUR','TRY','BRL','BIDR','IDRT','UAH','NGN','RUB','GBP','AUD','BUSD','USD1','RLUSD','USDE','XUSD','EURI','XAUT','PAXG','WBTC','WETH']);
const DAYS=1825,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,AGE=2190,LIQ=1e7;
const CFG={kind:'int',form:360,target:.12,hold:180,stop:.0275};
const G={minPF:1.15,minFolds:4,maxDD:.20,minNbr:.70,minPooledN:100};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function universe(){const ex=await get('/api/v3/exchangeInfo'),tk=await get('/api/v3/ticker/24hr'),m=new Map(ex.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed).map(x=>[x.symbol,x]));return tk.filter(x=>m.has(x.symbol)&&!EXCL.has(x.symbol)).filter(x=>{const b=m.get(x.symbol).baseAsset;return !BAD.has(b)&&!/(UP|DOWN|BULL|BEAR)$/.test(b)}).map(x=>({s:x.symbol,q:+x.quoteVolume})).filter(x=>x.q>0).sort((a,b)=>b.q-a.q).slice(0,80).map(x=>x.s)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],q:+k[7],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function prep(r){const adv=new Array(r.length).fill(NaN);for(let i=180;i<r.length;i++)adv[i]=r.slice(i-179,i+1).reduce((s,x)=>s+x.q,0)/30;return {adv}}
function rv(r,i,n){if(i<n)return NaN;const a=[];for(let j=i-n+1;j<=i;j++)if(j>0)a.push(r[j].c/r[j-1].c-1);const mu=mean(a);return Math.sqrt(mean(a.map(x=>(x-mu)**2)))}
function exit(r,ei,c){const en=r[ei].o,st=en*(1-c.stop),tg=en*(1+c.target);let ex=r[Math.min(ei+c.hold,r.length-1)].c,xt=r[Math.min(ei+c.hold,r.length-1)].t,why='TIME';for(let j=ei;j<Math.min(r.length,ei+c.hold+1);j++){if(r[j].l<=st){ex=st;xt=r[j].t;why='STOP';break}if(r[j].h>=tg){ex=tg;xt=r[j].t;why='TARGET';break}}return {entryT:r[ei].t,exitT:xt,gross:ex/en-1,reason:why}}
function sim(rows,preps,c,start=-Infinity){const br=rows.get('BTCUSDT');if(!br)return[];const be=ema(br.map(x=>x.c),600),maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,{...x,i}]))])),out=[];for(let bi=600;bi<br.length;bi++){if(bi%42!==0)continue;const b=br[bi];if(b.t<start)continue;if(!(b.c>be[bi]&&b.c/br[bi-180].c-1>0))continue;const cs=[];for(const [s,r] of rows){if(s==='BTCUSDT')continue;const q=maps.get(s).get(b.t);if(!q||q.i<Math.max(AGE,c.form))continue;if(!(preps.get(s).adv[q.i]>=LIQ))continue;const vol=rv(r,q.i,c.form);if(!(vol>0))continue;const mom=q.c/r[q.i-180].c-1;cs.push({s,r,q,vol,mom})}cs.sort((a,b)=>a.vol-b.vol);const low=cs.slice(0,Math.max(2,Math.ceil(cs.length*.25))).filter(x=>x.mom>0);low.sort((a,b)=>b.mom-a.mom);for(const x of low.slice(0,2)){const ei=x.q.i+1;if(ei<x.r.length)out.push({sym:x.s,...exit(x.r,ei,c)})}}return out.sort((a,b)=>a.entryT-b.entryT)}
function met(t,c){const r=t.map(x=>x.gross-c),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));let eq=ACCOUNT,pk=eq,dd=0;for(const x of r){eq=Math.max(0,eq+ORDER*x);pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk);if(eq<=0){dd=1;break}}return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:Math.min(1,dd),grossProfit:gp,grossLoss:gl}}
function folds(t,c){if(!t.length)return [...Array(5)].map(()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return [...Array(5)].map((_,f)=>{const x=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:x.length,expectancy:mean(x.map(z=>z.gross-c))}})}
function nbrs(){const o=[];for(const form of [300,360,420])for(const target of [.10,.12,.14])for(const hold of [150,180,210])o.push({...CFG,form,target,hold});return o}
function combine(a,b){return {n:a.n+b.n,expectancy:(a.expectancy*a.n+b.expectancy*b.n)/(a.n+b.n||1),pf:(a.grossLoss+b.grossLoss)?(a.grossProfit+b.grossProfit)/(a.grossLoss+b.grossLoss):999,maxDD:Math.max(a.maxDD,b.maxDD)}}
async function load(syms){const rows=new Map(),preps=new Map();for(const s of syms){try{const r=await kl(s);if(r.length>800){rows.set(s,r);preps.set(s,prep(r));console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}return {rows,preps}}
const repSyms=await universe();const rep=await load([...repSyms,'BTCUSDT']);const trades=sim(rep.rows,rep.preps,CFG),base=met(trades,BASE),stress=met(trades,STRESS),wf=folds(trades,BASE),posF=wf.filter(x=>x.n>0&&x.expectancy>0).length;
let npos=0,ntot=0;for(const c of nbrs()){const m=met(sim(rep.rows,rep.preps,c),BASE);npos+=(m.expectancy>0&&m.pf>1)?1:0;ntot++}const nfrac=ntot?npos/ntot:0;
const replicationPass=base.n>0&&base.expectancy>0&&base.pf>=G.minPF&&stress.expectancy>0&&posF>=G.minFolds&&base.maxDD<=G.maxDD;
const res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round16.json',replicationSymbols:repSyms,replicationUsable:[...rep.rows.keys()],replication:{base,doubleCost:stress,folds:wf,positiveFolds:posF,neighborFraction:nfrac,pass:replicationPass},pooled:null,finalHoldout:null,verdict:'REPLICATION_FAILED'};
if(replicationPass){const seen=await load(SEEN);if(!seen.rows.has('BTCUSDT')){const r=await kl('BTCUSDT');seen.rows.set('BTCUSDT',r);seen.preps.set('BTCUSDT',prep(r))}const br=seen.rows.get('BTCUSDT'),cut=br[0].t+(br.at(-1).t-br[0].t)*.70;const old=sim(seen.rows,seen.preps,CFG,cut),oldB=met(old,BASE),oldS=met(old,STRESS),pooledB=combine(oldB,base),pooledS=combine(oldS,stress);const pooledPass=pooledB.n>=G.minPooledN&&pooledB.pf>=G.minPF&&pooledB.expectancy>0&&pooledS.expectancy>0&&pooledB.maxDD<=G.maxDD&&nfrac>=G.minNbr;res.pooled={oldOos:oldB,replication:base,base:pooledB,doubleCost:pooledS,neighborFraction:nfrac,pass:pooledPass};res.verdict=pooledPass?'PROCEED_TO_FINAL_HOLDOUT':'POOLED_GATE_FAILED'}
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round16-replication.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
