import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const DISC=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','FILUSDT','ATOMUSDT','APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT'];
const HOLD=['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT'];
const DAYS=1825,OOS=.30,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,RESERVE=2;
const G={minN:100,minPF:1.15,minFolds:4,maxDD:.20,minNbr:.70};
const CFG={
 RANK_REVERSAL_24H:{h:6,k:2,cut:-.05,stop:.0275,target:.06,hold:6,vol:false},
 RANK_REVERSAL_48H:{h:12,k:2,cut:-.07,stop:.0275,target:.07,hold:8,vol:false},
 RANK_REVERSAL_VOLUME:{h:6,k:3,cut:-.04,stop:.0275,target:.06,hold:6,vol:true,vz:1}
};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function klines(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],v:+k[5],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;const med=a=>{if(!a.length)return NaN;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function prep(r){const c=r.map(x=>x.c),lv=r.map(x=>Math.log1p(x.v)),e200=ema(c,200),vz=new Array(r.length).fill(NaN);for(let i=42;i<r.length;i++){const h=lv.slice(i-42,i),mu=mean(h),sd=Math.sqrt(mean(h.map(x=>(x-mu)**2)));if(sd>0)vz[i]=(lv[i]-mu)/sd}return {e200,vz}}
function dd(rs){let eq=ACCOUNT,pk=ACCOUNT,m=0;for(const x of rs){eq=Math.max(0,eq+ORDER*x);pk=Math.max(pk,eq);m=Math.max(m,pk?1-eq/pk:1);if(eq<=0)return 1}return Math.min(1,m)}
function met(t,cost){const r=t.map(x=>x.gross-cost),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:dd(r)}}
function folds(t,c,start,end){const w=(end-start)/5,o=[];for(let f=0;f<5;f++){const a=start+f*w,b=f===4?end+1:start+(f+1)*w,x=t.filter(z=>z.entryT>=a&&z.entryT<b);o.push({n:x.length,expectancy:mean(x.map(z=>z.gross-c))})}return o}
function buildPanel(rows){const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,{...x,i}]))]));const ts=[...new Set([...rows.values()].flatMap(r=>r.map(x=>x.t)))].sort((a,b)=>a-b);return {maps,ts}}
function simulateCandidate(rows,preps,cfg,onlyAfter=-Infinity){const {maps,ts}=buildPanel(rows),btc=maps.get('BTCUSDT'),out=[];for(let ti=0;ti<ts.length;ti+=3){const t=ts[ti],b=btc?.get(t);if(!b||b.i<200)continue;const br=rows.get('BTCUSDT');if(!(b.c>preps.get('BTCUSDT').e200[b.i]))continue;const b24=b.i>=6?b.c/br[b.i-6].c-1:NaN;if(!(b24>-.02))continue;const candidates=[];for(const [s,r] of rows){const q=maps.get(s).get(t);if(!q||q.i<Math.max(42,cfg.h))continue;const ret=q.c/r[q.i-cfg.h].c-1;if(!Number.isFinite(ret))continue;candidates.push({s,q,r,ret})}if(candidates.length<8)continue;const basket=med(candidates.map(x=>x.ret));for(const x of candidates)x.res=x.ret-basket;candidates.sort((a,b)=>a.res-b.res);for(const x of candidates.slice(0,cfg.k)){const {s,q,r,res}=x;if(!(res<=cfg.cut))continue;const cur4=q.i>0?q.c/r[q.i-1].c-1:NaN;if(!(cur4>0))continue;if(cfg.vol){const candlePos=(q.c-q.l)/(Math.max(1e-12,q.h-q.l));if(!(candlePos>=.5&&preps.get(s).vz[q.i]>=cfg.vz))continue}const enI=q.i+1;if(enI>=r.length)continue;const en=r[enI].o;if(!(en>0))continue;const stop=en*(1-cfg.stop),target=en*(1+cfg.target);let exit=r[Math.min(enI+cfg.hold,r.length-1)].c,exitT=r[Math.min(enI+cfg.hold,r.length-1)].t,reason='TIME';for(let j=enI;j<Math.min(r.length,enI+cfg.hold+1);j++){if(r[j].l<=stop){exit=stop;exitT=r[j].t;reason='STOP';break}if(r[j].h>=target){exit=target;exitT=r[j].t;reason='TARGET';break}}const entryT=r[enI].t;if(entryT>=onlyAfter)out.push({sym:s,signalT:t,entryT,exitT,gross:exit/en-1,reason,residual:res})}}
}return out.sort((a,b)=>a.entryT-b.entryT)}
function nbrs(name){const o=[];if(name==='RANK_REVERSAL_24H')for(const cut of [-.04,-.05,-.06])for(const hold of [4,6,8])for(const stop of [.025,.0275,.03])o.push({...CFG[name],cut,hold,stop});if(name==='RANK_REVERSAL_48H')for(const cut of [-.06,-.07,-.08])for(const hold of [6,8,10])for(const stop of [.025,.0275,.03])o.push({...CFG[name],cut,hold,stop});if(name==='RANK_REVERSAL_VOLUME')for(const cut of [-.03,-.04,-.05])for(const vz of [.75,1,1.25])for(const hold of [4,6,8])o.push({...CFG[name],cut,vz,hold});return o}
function top2share(trades,cost=BASE){const p=trades.map(x=>Math.max(0,x.gross-cost)).sort((a,b)=>b-a),tot=p.reduce((s,x)=>s+x,0);return tot?((p[0]||0)+(p[1]||0))/tot:1}
async function load(symbols){const rows=new Map(),preps=new Map();for(const s of symbols){try{const r=await klines(s);if(r.length>1200){rows.set(s,r);preps.set(s,prep(r));console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}return {rows,preps}}
const d=await load(DISC);const minT=Math.min(...[...d.rows.values()].map(r=>r[0].t)),maxT=Math.max(...[...d.rows.values()].map(r=>r.at(-1).t)),cut=minT+(maxT-minT)*(1-OOS);
const res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round9.json',cutoff:new Date(cut).toISOString(),reports:{},discoveryWinners:[],holdout:null,verdict:'NO_STRATEGY_APPROVED'};
for(const name of Object.keys(CFG)){const all=simulateCandidate(d.rows,d.preps,CFG[name]),oos=all.filter(x=>x.entryT>=cut),base=met(oos,BASE),stress=met(oos,STRESS),fs=folds(oos,BASE,cut,maxT),pfolds=fs.filter(x=>x.n>0&&x.expectancy>0).length;let pos=0,total=0;for(const c of nbrs(name)){const nt=simulateCandidate(d.rows,d.preps,c,cut),m=met(nt,BASE);pos+=(m.expectancy>0&&m.pf>1)?1:0;total++}const frac=total?pos/total:0,pass=base.n>=G.minN&&base.pf>=G.minPF&&base.expectancy>0&&stress.expectancy>0&&pfolds>=G.minFolds&&base.maxDD<=G.maxDD&&frac>=G.minNbr;res.reports[name]={allTrades:all.length,oosBase:base,oosDoubleCost:stress,folds:fs,positiveFolds:pfolds,neighborFraction:frac,topTwoProfitShare:top2share(oos),discoveryPass:pass};if(pass)res.discoveryWinners.push(name)}
if(res.discoveryWinners.length){const h=await load(HOLD);res.holdout={};for(const name of res.discoveryWinners){const t=simulateCandidate(h.rows,h.preps,CFG[name]),m=met(t,BASE),ms=met(t,STRESS);const combinedN=res.reports[name].oosBase.n+m.n;const pass=m.n>0&&m.expectancy>0&&m.pf>=1.15&&ms.expectancy>0&&combinedN>=200&&top2share(t)<=.50;res.holdout[name]={metrics:m,doubleCost:ms,combinedOosTrades:combinedN,topTwoProfitShare:top2share(t),paperPass:pass};if(pass)res.verdict='PAPER_CANDIDATE_APPROVED'}}
else res.verdict='NO_STRATEGY_APPROVED';
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round9-discovery.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
