import fs from 'node:fs/promises';
const API=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const BAD=new Set(['USDC','FDUSD','TUSD','USDP','DAI','EUR','AEUR','TRY','BRL','BIDR','IDRT','UAH','NGN','RUB','GBP','AUD','BUSD','USD1','RLUSD','USDE','XUSD','EURI','XAUT','PAXG','WBTC','WETH']);
const HOLD=new Set(['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT']);
const IDS=['RMOM_LOWVOL_BREAKOUT','RMOM_DUAL_TREND','LOWVOL_MOM_TREND','DUAL_HORIZON_MOM','DONCHIAN55_RMOM','VOL_SQUEEZE_MOM','ADX_RMOM','VOLUME_BREAKOUT_TREND','PULLBACK_RMOM_TREND','MULTIFACTOR_MOM'];
const DAYS=1825,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,RESERVE=2,MAXRISK=.20,LIQ=1e7,AGE=2190,REB=42,HOLD_BARS=120,ATRM=2.5;
async function get(p){let e;for(const b of API){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function universe(){const ex=await get('/api/v3/exchangeInfo'),tk=await get('/api/v3/ticker/24hr'),m=new Map(ex.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed).map(x=>[x.symbol,x]));return tk.filter(x=>m.has(x.symbol)&&!HOLD.has(x.symbol)).filter(x=>{const b=m.get(x.symbol).baseAsset;return !BAD.has(b)&&!/(UP|DOWN|BULL|BEAR)$/.test(b)}).map(x=>({s:x.symbol,q:+x.quoteVolume})).filter(x=>x.q>0).sort((a,b)=>b.q-a.q).slice(0,30).map(x=>x.s)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],v:+k[5],q:+k[7],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN;const sd=a=>{const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))};
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function sma(v,p){const o=new Array(v.length).fill(NaN);let s=0;for(let i=0;i<v.length;i++){s+=v[i];if(i>=p)s-=v[i-p];if(i>=p-1)o[i]=s/p}return o}
function atr(r,p=14){const tr=r.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-r[i-1].c),Math.abs(x.l-r[i-1].c)):x.h-x.l);return ema(tr,p)}
function adx(r,p=14){const n=r.length,trs=[],pd=[],md=[];for(let i=0;i<n;i++){if(!i){trs.push(r[i].h-r[i].l);pd.push(0);md.push(0);continue}trs.push(Math.max(r[i].h-r[i].l,Math.abs(r[i].h-r[i-1].c),Math.abs(r[i].l-r[i-1].c)));const up=r[i].h-r[i-1].h,dn=r[i-1].l-r[i].l;pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}const a=ema(trs,p),ap=ema(pd,p),am=ema(md,p),pdi=a.map((x,i)=>x?100*ap[i]/x:NaN),mdi=a.map((x,i)=>x?100*am[i]/x:NaN),dx=pdi.map((x,i)=>(x+mdi[i])?100*Math.abs(x-mdi[i])/(x+mdi[i]):NaN);return {adx:ema(dx.map(x=>Number.isFinite(x)?x:0),p),pdi,mdi}}
function hi(r,i,n){if(i<n)return NaN;let h=-Infinity;for(let j=i-n;j<i;j++)h=Math.max(h,r[j].h);return h}
function prep(r){const c=r.map(x=>x.c),v=r.map(x=>x.v),e50=ema(c,50),e200=ema(c,200),a14=atr(r),vol20=sma(v,20),{adx:ax,pdi,mdi}=adx(r);const adv=new Array(r.length).fill(NaN),rv180=new Array(r.length).fill(NaN),bbW=new Array(r.length).fill(NaN);for(let i=0;i<r.length;i++){if(i>=179)adv[i]=r.slice(i-179,i+1).reduce((s,x)=>s+x.q,0)/30;if(i>=180){const rr=[];for(let j=i-179;j<=i;j++)rr.push(c[j]/c[j-1]-1);rv180[i]=sd(rr)}if(i>=19){const z=c.slice(i-19,i+1),d=sd(z);bbW[i]=d?4*d/mean(z):NaN}}return {e50,e200,a14,vol20,ax,pdi,mdi,adv,rv180,bbW}}
function regime(br,bp,i){return i>=180&&br[i].c>bp.e200[i]&&br[i].c/br[i-180].c-1>0}
function trailingExit(r,p,ei,useTrendExit=true){const en=r[ei].o,a0=p.a14[Math.max(0,ei-1)];if(!Number.isFinite(a0)||a0<=0)return null;let stop=en-ATRM*a0,highClose=en,last=Math.min(r.length-1,ei+HOLD_BARS),ex=r[last].c,xt=r[last].t,why='TIME';for(let j=ei;j<=last;j++){if(r[j].o<stop){ex=r[j].o;xt=r[j].t;why='GAP_STOP';break}if(r[j].l<=stop){ex=stop;xt=r[j].t;why='TRAIL_STOP';break}if(useTrendExit&&j>ei&&Number.isFinite(p.e50[j-1])&&r[j-1].c<p.e50[j-1]){ex=r[j].o;xt=r[j].t;why='EMA50_EXIT';break}highClose=Math.max(highClose,r[j].c);if(Number.isFinite(p.a14[j]))stop=Math.max(stop,highClose-ATRM*p.a14[j])}const stopFrac=Math.max(.0001,(ATRM*a0)/en);const notional=Math.max(0,Math.min(ORDER,MAXRISK/stopFrac,ACCOUNT-RESERVE));return {entryT:r[ei].t,exitT:xt,gross:ex/en-1,reason:why,notional}}
function scoreStats(cand){const vals=k=>cand.map(x=>x[k]).filter(Number.isFinite),z=(x,a)=>{const m=mean(a),d=sd(a);return d?((x-m)/d):0};const moms=vals('mom30'),rms=vals('rmom'),tr=vals('trend'),vr=vals('volRatio'),vols=vals('vol');for(const x of cand)x.multi=z(x.rmom,rms)+.7*z(x.mom30,moms)+.5*z(x.trend,tr)+.35*z(x.volRatio,vr)-.35*z(x.vol,vols);return cand}
function select(id,cand){if(!cand.length)return[];const low=[...cand].sort((a,b)=>a.vol-b.vol).slice(0,Math.max(3,Math.ceil(cand.length*.35)));switch(id){case'RMOM_LOWVOL_BREAKOUT':return low.filter(x=>x.mom30>0&&x.break20&&x.volRatio>1.15&&x.trend>0).sort((a,b)=>b.rmom-a.rmom).slice(0,2);case'RMOM_DUAL_TREND':return cand.filter(x=>x.mom30>0&&x.trend>0&&x.e50gt200).sort((a,b)=>b.rmom-a.rmom).slice(0,2);case'LOWVOL_MOM_TREND':return low.filter(x=>x.mom30>0&&x.trend>0).sort((a,b)=>b.mom30-a.mom30).slice(0,2);case'DUAL_HORIZON_MOM':return cand.filter(x=>x.mom30>0&&x.mom90>0&&x.trend>0).sort((a,b)=>(b.mom30+b.mom90)-(a.mom30+a.mom90)).slice(0,2);case'DONCHIAN55_RMOM':return cand.filter(x=>x.break55&&x.mom30>0&&x.trend>0).sort((a,b)=>b.rmom-a.rmom).slice(0,2);case'VOL_SQUEEZE_MOM':{const ws=cand.map(x=>x.bbw).filter(Number.isFinite).sort((a,b)=>a-b),thr=ws[Math.floor(ws.length*.3)]??Infinity;return cand.filter(x=>x.bbw<=thr&&x.break20&&x.mom30>0&&x.trend>0).sort((a,b)=>b.rmom-a.rmom).slice(0,2)}case'ADX_RMOM':return cand.filter(x=>x.adx>25&&x.pdi>x.mdi&&x.mom30>0&&x.trend>0).sort((a,b)=>b.rmom-a.rmom).slice(0,2);case'VOLUME_BREAKOUT_TREND':return cand.filter(x=>x.break20&&x.volRatio>1.5&&x.trend>0&&x.mom30>0).sort((a,b)=>b.volRatio-a.volRatio).slice(0,2);case'PULLBACK_RMOM_TREND':return cand.filter(x=>x.e50gt200&&x.trend>0&&x.dist50>=-.01&&x.dist50<=.025&&x.mom30>0).sort((a,b)=>b.rmom-a.rmom).slice(0,2);case'MULTIFACTOR_MOM':return scoreStats(cand.filter(x=>x.mom30>0&&x.trend>0)).sort((a,b)=>b.multi-a.multi).slice(0,2);default:return[]}}
function metrics(t,cost){const rs=t.map(z=>({r:z.gross-cost,n:z.notional||ORDER})),w=rs.filter(x=>x.r>0),l=rs.filter(x=>x.r<0),gp=w.reduce((s,x)=>s+x.r,0),gl=Math.abs(l.reduce((s,x)=>s+x.r,0));let eq=ACCOUNT,pk=eq,dd=0;for(const x of rs){eq=Math.max(0,eq+x.n*x.r);pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}return {n:rs.length,expectancy:rs.length?mean(rs.map(x=>x.r)):0,pf:gl?gp/gl:(gp>0?999:0),winRate:rs.length?w.length/rs.length:0,maxDD:dd,grossProfit:gp,grossLoss:gl}}
function folds(t,cost){if(!t.length)return Array.from({length:5},()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return Array.from({length:5},(_,f)=>{const q=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:q.length,expectancy:q.length?mean(q.map(z=>z.gross-cost)):0}})}
const syms=await universe(),rows=new Map(),ps=new Map();for(const s of [...new Set(['BTCUSDT',...syms])]){try{const r=await kl(s);if(r.length>AGE+250){rows.set(s,r);ps.set(s,prep(r));console.error('loaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}
const br=rows.get('BTCUSDT'),bp=ps.get('BTCUSDT');if(!br)throw new Error('BTC data missing');const cut=br[0].t+(br.at(-1).t-br[0].t)*.70,maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,i]))]));
const out={generatedAt:new Date().toISOString(),protocol:'validation/evidence-gate-round19.json',universe:syms,usable:[...rows.keys()],oosCut:new Date(cut).toISOString(),results:[],promotable:[],verdict:'NO_STRATEGY_APPROVED'};
for(const id of IDS){const tr=[];for(let bi=AGE;bi<br.length-1;bi++){if(br[bi].t<cut||bi%REB!==0||!regime(br,bp,bi))continue;const cand=[];for(const [s,r] of rows){if(s==='BTCUSDT')continue;const i=maps.get(s).get(br[bi].t);if(i==null||i<AGE||i+1>=r.length)continue;const p=ps.get(s);if(!(p.adv[i]>=LIQ)||!Number.isFinite(p.rv180[i])||p.rv180[i]<=0)continue;const mom30=r[i].c/r[i-180].c-1,mom90=i>=540?r[i].c/r[i-540].c-1:NaN,trend=r[i].c/p.e200[i]-1,rmom=mom30/p.rv180[i],volRatio=p.vol20[i]?r[i].v/p.vol20[i]:0,dist50=r[i].c/p.e50[i]-1;cand.push({s,r,p,i,mom30,mom90,trend,rmom,vol:p.rv180[i],volRatio,break20:r[i].c>hi(r,i,20),break55:r[i].c>hi(r,i,55),e50gt200:p.e50[i]>p.e200[i],dist50,adx:p.ax[i],pdi:p.pdi[i],mdi:p.mdi[i],bbw:p.bbW[i]})}for(const x of select(id,cand)){const z=trailingExit(x.r,x.p,x.i+1,true);if(z)tr.push({sym:x.s,...z})}}
tr.sort((a,b)=>a.entryT-b.entryT);const base=metrics(tr,BASE),stress=metrics(tr,STRESS),wf=folds(tr,BASE),pos=wf.filter(x=>x.n>0&&x.expectancy>0).length,pass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&stress.expectancy>0&&pos>=4&&base.maxDD<=.20;out.results.push({id,base,doubleCost:stress,folds:wf,positiveFolds:pos,pass});if(pass)out.promotable.push(id)}
out.results.sort((a,b)=>(b.pass-a.pass)||(b.doubleCost.pf-a.doubleCost.pf)||(b.base.pf-a.base.pf)||(b.base.n-a.base.n));if(out.promotable.length)out.verdict='PROMOTABLE_STRATEGIES_FOUND';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round19-tournament.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
