import fs from 'node:fs';
const BASE='https://api.binance.com';
const symbols=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','TRXUSDT','XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT'];
const tf='4h', limit=1000;
async function klines(s){const u=`${BASE}/api/v3/klines?symbol=${s}&interval=${tf}&limit=${limit}`; const r=await fetch(u); if(!r.ok) throw new Error(`${s} ${r.status}`); return (await r.json()).map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4]}));}
function ema(a,n){let out=[],k=2/(n+1),v=a[0];for(const x of a){v=x*k+v*(1-k);out.push(v)}return out}
function atr(a,n=14){let tr=a.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-a[i-1].c),Math.abs(x.l-a[i-1].c)):x.h-x.l);let out=[],v=tr[0];for(let i=0;i<tr.length;i++){v=i<n?tr.slice(0,i+1).reduce((p,q)=>p+q,0)/(i+1):(v*(n-1)+tr[i])/n;out.push(v)}return out}
function stats(ts,cost){let rs=ts.map(x=>x.gross-cost), wins=rs.filter(x=>x>0).reduce((a,b)=>a+b,0), losses=-rs.filter(x=>x<0).reduce((a,b)=>a+b,0), eq=0,peak=0,dd=0;for(const r of rs){eq+=r;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return {n:rs.length,expectancy:rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:null,pf:losses?wins/losses:null,maxDD:dd};}
let all=[];for(const s of symbols){const a=await klines(s), c=a.map(x=>x.c), e200=ema(c,200), e50=ema(c,50), at=atr(a);let ts=[];for(let i=200;i<a.length-1;i++){let m42=c[i]/c[i-42]-1,m126=c[i]/c[i-126]-1;if(!(m42>0&&m126>0&&c[i]>e200[i]))continue;let entry=a[i+1].o, stop=entry-2.5*at[i], exit=null;for(let j=i+1;j<Math.min(a.length,i+92);j++){stop=Math.max(stop,a[j].c-2.5*at[j]);if(a[j].l<=stop){exit=stop;break}if(a[j].c<e50[j]){exit=a[j].c;break}if(j===Math.min(a.length-1,i+91))exit=a[j].c;}if(exit){ts.push({symbol:s,t:a[i+1].t,gross:(exit/entry-1)*100});i+=2}}
all.push(...ts);}
all.sort((a,b)=>a.t-b.t);const base=stats(all,.36),stress=stats(all,.72);let folds=[];for(let f=0;f<5;f++){let x=all.slice(Math.floor(f*all.length/5),Math.floor((f+1)*all.length/5));folds.push(stats(x,.36));}let bySymbol={};for(const s of symbols)bySymbol[s]=stats(all.filter(x=>x.symbol===s),.36);let posSym=Object.values(bySymbol).filter(x=>x.n&&x.expectancy>0).length/Object.values(bySymbol).filter(x=>x.n).length;let pass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&stress.expectancy>0&&folds.filter(x=>x.expectancy>0).length>=4&&base.maxDD<=20&&posSym>=.60;const out={round:21,strategy:'DUAL_HORIZON_MOM',base,stress,positiveFolds:folds.filter(x=>x.expectancy>0).length,folds,positiveSymbolsFraction:posSym,bySymbol,pass,verdict:pass?'CANDIDATE_FOR_PAPER_FORWARD':'REJECTED',liveTrading:false};fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/round21.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));