import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const SYMBOLS=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','FILUSDT','ATOMUSDT','APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT'];
const DAYS=1825,OOS=.30,BASE=.003,STRESS=.006,ACCOUNT=20.12,ORDER=7,G={minN:100,minPF:1.15,minFolds:4,maxDD:.20,minNbr:.70};
const CFG={TSMOM_60_REGIME:{momentumBars:60,triggerReturn:.08,trailAtr:3.5,stopAtr:2,maxHoldBars:120},EMA50_RECLAIM_12H:{touchAtr:.4,reclaimBars:4,trailAtr:3,stopAtr:1.75,maxHoldBars:96},HIGH52_TREND_12H:{breakoutBars:40,trailAtr:3.75,stopAtr:2.25,maxHoldBars:160}};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function klines(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=12h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}function atr(r,p=14){const tr=r.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-r[i-1].c),Math.abs(x.l-r[i-1].c)):x.h-x.l);return ema(tr,p)}
function prep(r){const c=r.map(x=>x.c);return {e50:ema(c,50),e200:ema(c,200),a:atr(r,14)}}
function dd(rs){let eq=ACCOUNT,pk=ACCOUNT,m=0;for(const x of rs){eq+=ORDER*x;pk=Math.max(pk,eq);if(eq<=0)return 1;m=Math.max(m,1-eq/pk)}return m}function met(t,cost){const r=t.map(x=>x.gross-cost),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:dd(r)}}function folds(t,c,start,end){const w=(end-start)/5,o=[];for(let f=0;f<5;f++){const a=start+f*w,b=f===4?end+1:start+(f+1)*w,x=t.filter(z=>z.t>=a&&z.t<b);o.push({n:x.length,expectancy:mean(x.map(z=>z.gross-c))})}return o}
function sig(n,r,p,i,c){if(i<220||p.e50[i]<=p.e200[i]||r[i].c<=p.e200[i])return false;if(n==='TSMOM_60_REGIME'){const m=r[i].c/r[i-c.momentumBars].c-1,m20=r[i].c/r[i-20].c-1,hi=Math.max(...r.slice(i-10,i).map(x=>x.h));return m>c.triggerReturn&&m20>0&&r[i].c>hi}if(n==='EMA50_RECLAIM_12H'){if(p.e50[i]<=p.e50[i-10])return false;let touch=false;for(let j=i-4;j<i;j++)if(r[j].l<=p.e50[j]+c.touchAtr*p.a[j])touch=true;const hi=Math.max(...r.slice(i-c.reclaimBars,i).map(x=>x.h));return touch&&r[i].c>hi}const hi=Math.max(...r.slice(i-c.breakoutBars,i).map(x=>x.h));return r[i].c>hi&&p.a[i]/r[i].c<.12}
function sim(n,r,p,c){const out=[];let pos=null;for(let i=220;i<r.length-1;i++){if(pos){const b=r[i];if(b.l<=pos.stop){out.push({t:b.t,gross:pos.stop/pos.entry-1});pos=null;continue}pos.peak=Math.max(pos.peak,b.h);pos.stop=Math.max(pos.stop,pos.peak-c.trailAtr*p.a[i]);pos.held++;let ex=false;if(n==='TSMOM_60_REGIME')ex=i>=20&&(b.c/r[i-20].c-1)<0;else ex=b.c<p.e50[i];if(ex||pos.held>=c.maxHoldBars){out.push({t:b.t,gross:b.c/pos.entry-1});pos=null;continue}}if(!pos&&sig(n,r,p,i,c)){const en=r[i+1].o,aa=p.a[i];if(en>0&&aa>0)pos={entry:en,stop:en-c.stopAtr*aa,peak:en,held:0}}}return out}
function nbrs(n){const o=[];if(n==='TSMOM_60_REGIME')for(const m of [48,60,72])for(const q of [.06,.08,.10])for(const t of [3,3.5,4])o.push({...CFG[n],momentumBars:m,triggerReturn:q,trailAtr:t});if(n==='EMA50_RECLAIM_12H')for(const a of [.25,.4,.55])for(const b of [3,4,5])for(const t of [2.75,3,3.25])o.push({...CFG[n],touchAtr:a,reclaimBars:b,trailAtr:t});if(n==='HIGH52_TREND_12H')for(const b of [32,40,48])for(const s of [2,2.25,2.5])for(const t of [3.25,3.75,4.25])o.push({...CFG[n],breakoutBars:b,stopAtr:s,trailAtr:t});return o}
const rows=new Map(),preps=new Map();for(const s of SYMBOLS){try{const r=await klines(s);if(r.length>600){rows.set(s,r);preps.set(s,prep(r));console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}const minT=Math.min(...[...rows.values()].map(r=>r[0].t)),maxT=Math.max(...[...rows.values()].map(r=>r.at(-1).t)),cut=minT+(maxT-minT)*(1-OOS),res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round8.json',cutoff:new Date(cut).toISOString(),reports:{}};
for(const n of Object.keys(CFG)){const all=[];for(const [s,r] of rows)for(const x of sim(n,r,preps.get(s),CFG[n]))all.push({...x,sym:s});all.sort((a,b)=>a.t-b.t);const oos=all.filter(x=>x.t>=cut),base=met(oos,BASE),stress=met(oos,STRESS),fs=folds(oos,BASE,cut,maxT),pfolds=fs.filter(x=>x.n>0&&x.expectancy>0).length;let pos=0,total=0;for(const c of nbrs(n)){const nt=[];for(const [s,r] of rows)for(const x of sim(n,r,preps.get(s),c))if(x.t>=cut)nt.push(x);const m=met(nt,BASE);pos+=(m.expectancy>0&&m.pf>1)?1:0;total++}const frac=pos/total,pass=base.n>=G.minN&&base.pf>=G.minPF&&base.expectancy>0&&stress.expectancy>0&&pfolds>=G.minFolds&&base.maxDD<=G.maxDD&&frac>=G.minNbr;res.reports[n]={allTrades:all.length,oosBase:base,oosDoubleCost:stress,folds:fs,positiveFolds:pfolds,neighborFraction:frac,discoveryPass:pass}}
res.discoveryWinners=Object.entries(res.reports).filter(([,v])=>v.discoveryPass).map(([k])=>k);res.verdict=res.discoveryWinners.length?'PROCEED_TO_UNTOUCHED_SYMBOL_HOLDOUT':'NO_STRATEGY_APPROVED';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round8-discovery.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
