import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const SEEN=new Set(['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','FILUSDT','ATOMUSDT','APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT']);
const HOLD=['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT'];const HOLDSET=new Set(HOLD);
const BADBASE=new Set(['USDC','FDUSD','TUSD','USDP','DAI','EUR','AEUR','TRY','BRL','BIDR','IDRT','UAH','NGN','RUB','GBP','AUD','BUSD','USD1','RLUSD']);
const DAYS=1825,OOS=.30,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,CFG={h:12,k:2,cut:-.07,stop:.0275,target:.07,hold:8};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function pick(){const ex=await get('/api/v3/exchangeInfo'),tk=await get('/api/v3/ticker/24hr'),tradable=new Map(ex.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed).map(x=>[x.symbol,x]));return tk.filter(x=>tradable.has(x.symbol)&&!SEEN.has(x.symbol)&&!HOLDSET.has(x.symbol)).filter(x=>{const b=tradable.get(x.symbol).baseAsset;return !BADBASE.has(b)&&!/(UP|DOWN|BULL|BEAR)$/.test(b)}).map(x=>({s:x.symbol,q:+x.quoteVolume})).filter(x=>Number.isFinite(x.q)&&x.q>0).sort((a,b)=>b.q-a.q).slice(0,40).map(x=>x.s)}
async function klines(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;const med=a=>{if(!a.length)return NaN;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function dd(rs){let eq=ACCOUNT,pk=ACCOUNT,m=0;for(const x of rs){eq=Math.max(0,eq+ORDER*x);pk=Math.max(pk,eq);m=Math.max(m,1-eq/pk);if(eq<=0)return 1}return Math.min(1,m)}
function met(t,c){const r=t.map(x=>x.gross-c),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:dd(r)}}
function folds(t,c,start,end){const width=(end-start)/5,o=[];for(let f=0;f<5;f++){const a=start+f*width,b=f===4?end+1:start+(f+1)*width,x=t.filter(z=>z.entryT>=a&&z.entryT<b);o.push({n:x.length,expectancy:mean(x.map(z=>z.gross-c))})}return o}
async function load(symbols){const rows=new Map();for(const s of ['BTCUSDT',...symbols]){try{const r=await klines(s);if(r.length>500){rows.set(s,r);console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}return rows}
function sim(rows){const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,{...x,i}]))]));const ts=[...new Set([...rows.values()].flatMap(r=>r.map(x=>x.t)))].sort((a,b)=>a-b),btc=maps.get('BTCUSDT'),br=rows.get('BTCUSDT'),be=ema(br.map(x=>x.c),200),out=[];for(let ti=0;ti<ts.length;ti+=3){const t=ts[ti],b=btc?.get(t);if(!b||b.i<200||!(b.c>be[b.i]))continue;const b24=b.i>=6?b.c/br[b.i-6].c-1:NaN;if(!(b24>-.02))continue;const cs=[];for(const [s,r] of rows){if(s==='BTCUSDT')continue;const q=maps.get(s).get(t);if(!q||q.i<CFG.h)continue;const ret=q.c/r[q.i-CFG.h].c-1;if(Number.isFinite(ret))cs.push({s,r,q,ret})}if(cs.length<8)continue;const basket=med(cs.map(x=>x.ret));for(const x of cs)x.res=x.ret-basket;cs.sort((a,b)=>a.res-b.res);for(const x of cs.slice(0,CFG.k)){const {s,r,q,res}=x;if(!(res<=CFG.cut))continue;const cur=q.i>0?q.c/r[q.i-1].c-1:NaN;if(!(cur>0))continue;const ei=q.i+1;if(ei>=r.length)continue;const en=r[ei].o,stop=en*(1-CFG.stop),target=en*(1+CFG.target);let exit=r[Math.min(ei+CFG.hold,r.length-1)].c,exitT=r[Math.min(ei+CFG.hold,r.length-1)].t;for(let j=ei;j<Math.min(r.length,ei+CFG.hold+1);j++){if(r[j].l<=stop){exit=stop;exitT=r[j].t;break}if(r[j].h>=target){exit=target;exitT=r[j].t;break}}out.push({sym:s,entryT:r[ei].t,exitT,gross:exit/en-1,residual:res})}}return out.sort((a,b)=>a.entryT-b.entryT)}
const symbols=await pick();console.error('selected',symbols.join(','));const rows=await load(symbols);const usable=symbols.filter(s=>rows.has(s));const minT=Math.min(...usable.map(s=>rows.get(s)[0].t)),maxT=Math.max(...usable.map(s=>rows.get(s).at(-1).t)),cut=minT+(maxT-minT)*(1-OOS),all=sim(rows),oos=all.filter(x=>x.entryT>=cut),base=met(oos,BASE),stress=met(oos,STRESS),wf=folds(oos,BASE,cut,maxT),pfolds=wf.filter(x=>x.n>0&&x.expectancy>0).length,pass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&stress.expectancy>0&&pfolds>=4&&base.maxDD<=.20;
const res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round10.json',selectedSymbols:symbols,usableSymbols:usable,cutoff:new Date(cut).toISOString(),replication:{allTrades:all.length,oosBase:base,oosDoubleCost:stress,folds:wf,positiveFolds:pfolds,pass},finalHoldout:null,verdict:pass?'PROCEED_TO_FINAL_HOLDOUT':'REPLICATION_FAILED'};
if(pass){const hr=await load(HOLD);const ht=sim(hr),hm=met(ht,BASE),hs=met(ht,STRESS);const hpass=hm.n>0&&hm.expectancy>0&&hm.pf>=1.15&&hs.expectancy>0;res.finalHoldout={trades:ht.length,base:hm,doubleCost:hs,pass:hpass};res.verdict=hpass?'PAPER_CANDIDATE_APPROVED':'FINAL_HOLDOUT_FAILED'}
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round10-replication.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
