import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const S=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','FILUSDT','ATOMUSDT','APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT'];
const DAYS=1825,OOS=.30,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,G={minN:100,minPF:1.15,minFolds:4,maxDD:.20,minNbr:.70};
const CFG={ROTATION_30D:{type:'rot',mom:180,reb:42,k:2,min:.10,stop:.0275,target:.12,hold:42},ROTATION_90D:{type:'rot',mom:540,reb:84,k:2,min:.20,stop:.0275,target:.18,hold:84},BREAKOUT_20D:{type:'bo',look:120,min30:.08,stop:.0275,target:.10,hold:42,cool:42}};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function dd(rs){let eq=ACCOUNT,pk=ACCOUNT,m=0;for(const x of rs){eq=Math.max(0,eq+ORDER*x);pk=Math.max(pk,eq);m=Math.max(m,1-eq/pk);if(eq<=0)return 1}return Math.min(1,m)}function met(t,c){const r=t.map(x=>x.gross-c),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:dd(r)}}
function folds(t,c,a,b){const w=(b-a)/5,o=[];for(let f=0;f<5;f++){const x=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));o.push({n:x.length,expectancy:mean(x.map(z=>z.gross-c))})}return o}
function exitTrade(r,ei,c){const en=r[ei].o,st=en*(1-c.stop),tg=en*(1+c.target);let ex=r[Math.min(ei+c.hold,r.length-1)].c,xt=r[Math.min(ei+c.hold,r.length-1)].t;for(let j=ei;j<Math.min(r.length,ei+c.hold+1);j++){if(r[j].l<=st){ex=st;xt=r[j].t;break}if(r[j].h>=tg){ex=tg;xt=r[j].t;break}}return {entryT:r[ei].t,exitT:xt,gross:ex/en-1}}
function sim(name,rows,c){const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,{...x,i}]))]));const ts=[...new Set([...rows.values()].flatMap(r=>r.map(x=>x.t)))].sort((a,b)=>a-b),br=rows.get('BTCUSDT'),bm=maps.get('BTCUSDT'),be=ema(br.map(x=>x.c),600),out=[],last=new Map();for(let ti=0;ti<ts.length;ti++){const t=ts[ti],b=bm.get(t);if(!b||b.i<600||!(b.c>be[b.i]))continue;const b30=b.i>=180?b.c/br[b.i-180].c-1:NaN;if(!(b30>0))continue;if(c.type==='rot'){if(ti%c.reb!==0)continue;const cs=[];for(const [s,r] of rows){if(s==='BTCUSDT')continue;const q=maps.get(s).get(t);if(!q||q.i<c.mom)continue;const m=q.c/r[q.i-c.mom].c-1;if(m>=c.min)cs.push({s,r,q,m})}cs.sort((a,b)=>b.m-a.m);for(const x of cs.slice(0,c.k)){const ei=x.q.i+1;if(ei<x.r.length)out.push({sym:x.s,...exitTrade(x.r,ei,c)})}}else{for(const [s,r] of rows){if(s==='BTCUSDT')continue;const q=maps.get(s).get(t);if(!q||q.i<Math.max(c.look,180))continue;if((last.get(s)||-1)+c.cool>q.i)continue;const hi=Math.max(...r.slice(q.i-c.look,q.i).map(x=>x.h)),m30=q.c/r[q.i-180].c-1;if(q.c>hi&&m30>=c.min30){const ei=q.i+1;if(ei<r.length){out.push({sym:s,...exitTrade(r,ei,c)});last.set(s,q.i)}}}}}return out.sort((a,b)=>a.entryT-b.entryT)}
function nbrs(n){const c=CFG[n],o=[];if(n==='ROTATION_30D')for(const m of [.08,.10,.12])for(const h of [36,42,48])for(const t of [.10,.12,.14])o.push({...c,min:m,hold:h,target:t});if(n==='ROTATION_90D')for(const m of [.16,.20,.24])for(const h of [72,84,96])for(const t of [.15,.18,.21])o.push({...c,min:m,hold:h,target:t});if(n==='BREAKOUT_20D')for(const l of [96,120,144])for(const m of [.06,.08,.10])for(const t of [.08,.10,.12])o.push({...c,look:l,min30:m,target:t});return o}
const rows=new Map();for(const s of S){try{const r=await kl(s);if(r.length>1000){rows.set(s,r);console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}const minT=Math.min(...[...rows.values()].map(r=>r[0].t)),maxT=Math.max(...[...rows.values()].map(r=>r.at(-1).t)),cut=minT+(maxT-minT)*(1-OOS),res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round11.json',cutoff:new Date(cut).toISOString(),reports:{},winners:[],verdict:'NO_STRATEGY_APPROVED'};
for(const n of Object.keys(CFG)){const all=sim(n,rows,CFG[n]),oos=all.filter(x=>x.entryT>=cut),b=met(oos,BASE),s=met(oos,STRESS),wf=folds(oos,BASE,cut,maxT),pf=wf.filter(x=>x.n>0&&x.expectancy>0).length;let frac=0;if(b.n>=G.minN&&b.pf>=G.minPF&&b.expectancy>0&&s.expectancy>0&&pf>=G.minFolds&&b.maxDD<=G.maxDD){let p=0,z=0;for(const c of nbrs(n)){const m=met(sim(n,rows,c).filter(x=>x.entryT>=cut),BASE);p+=(m.expectancy>0&&m.pf>1)?1:0;z++}frac=z?p/z:0}const pass=b.n>=G.minN&&b.pf>=G.minPF&&b.expectancy>0&&s.expectancy>0&&pf>=G.minFolds&&b.maxDD<=G.maxDD&&frac>=G.minNbr;res.reports[n]={allTrades:all.length,oosBase:b,oosDoubleCost:s,folds:wf,positiveFolds:pf,neighborFraction:frac,pass};if(pass)res.winners.push(n)}res.verdict=res.winners.length?'PROCEED_TO_FINAL_HOLDOUT':'NO_STRATEGY_APPROVED';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round11-discovery.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
