import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const HOLD=['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT'],HOLDSET=new Set(HOLD);
const BAD=new Set(['USDC','FDUSD','TUSD','USDP','DAI','EUR','AEUR','TRY','BRL','BIDR','IDRT','UAH','NGN','RUB','GBP','AUD','BUSD','USD1','RLUSD','USDE','XUSD','EURI','XAUT','PAXG','WBTC','WETH']);
const DAYS=1825,OOS=.30,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,AGE=2190,LIQ=1e7;
const C={RSJ_PROXY_LOW:{kind:'low',form:180,bull:false,target:.12,hold:180},RSJ_PROXY_LOW_BULL:{kind:'low',form:180,bull:true,target:.12,hold:180},RSJ_PROXY_LOW_MOM:{kind:'mom',form:180,bull:true,target:.12,hold:180}};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function universe(){const ex=await get('/api/v3/exchangeInfo'),tk=await get('/api/v3/ticker/24hr'),m=new Map(ex.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed).map(x=>[x.symbol,x]));return tk.filter(x=>m.has(x.symbol)&&!HOLDSET.has(x.symbol)).filter(x=>{const b=m.get(x.symbol).baseAsset;return !BAD.has(b)&&!/(UP|DOWN|BULL|BEAR)$/.test(b)}).map(x=>({s:x.symbol,q:+x.quoteVolume})).filter(x=>x.q>0).sort((a,b)=>b.q-a.q).slice(0,80).map(x=>x.s)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],q:+k[7],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function prep(r){const adv=new Array(r.length).fill(NaN);for(let i=180;i<r.length;i++)adv[i]=r.slice(i-179,i+1).reduce((s,x)=>s+x.q,0)/30;return {adv}}
function rsj(r,i,n){if(i<n)return NaN;let pos=0,neg=0;for(let j=i-n+1;j<=i;j++){if(j<=0)continue;const x=r[j].c/r[j-1].c-1,q=x*x;if(x>=0)pos+=q;else neg+=q}const tot=pos+neg;return tot>0?(pos-neg)/tot:NaN}
function exit(r,ei,c){const en=r[ei].o,st=en*(1-.0275),tg=en*(1+c.target);let ex=r[Math.min(ei+c.hold,r.length-1)].c,xt=r[Math.min(ei+c.hold,r.length-1)].t;for(let j=ei;j<Math.min(r.length,ei+c.hold+1);j++){if(r[j].l<=st){ex=st;xt=r[j].t;break}if(r[j].h>=tg){ex=tg;xt=r[j].t;break}}return {entryT:r[ei].t,exitT:xt,gross:ex/en-1}}
function sim(rows,preps,c){const br=rows.get('BTCUSDT');if(!br)return[];const be=ema(br.map(x=>x.c),600),maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,{...x,i}]))])),out=[];for(let bi=600;bi<br.length;bi++){if(bi%42!==0)continue;const b=br[bi],bull=b.c>be[bi]&&b.c/br[bi-180].c-1>0;if(c.bull&&!bull)continue;const cs=[];for(const [s,r] of rows){if(s==='BTCUSDT')continue;const q=maps.get(s).get(b.t);if(!q||q.i<Math.max(AGE,c.form,180))continue;if(!(preps.get(s).adv[q.i]>=LIQ))continue;const score=rsj(r,q.i,c.form),mom=q.c/r[q.i-180].c-1;if(Number.isFinite(score))cs.push({s,r,q,score,mom})}cs.sort((a,b)=>a.score-b.score);if(c.kind==='low'){for(const x of cs.slice(0,2)){const ei=x.q.i+1;if(ei<x.r.length)out.push({sym:x.s,score:x.score,...exit(x.r,ei,c)})}}else{const low=cs.slice(0,Math.max(2,Math.ceil(cs.length*.25))).filter(x=>x.mom>0);low.sort((a,b)=>b.mom-a.mom);for(const x of low.slice(0,2)){const ei=x.q.i+1;if(ei<x.r.length)out.push({sym:x.s,score:x.score,...exit(x.r,ei,c)})}}}return out.sort((a,b)=>a.entryT-b.entryT)}
function met(t,c){const r=t.map(x=>x.gross-c),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));let eq=ACCOUNT,pk=eq,dd=0;for(const x of r){eq=Math.max(0,eq+ORDER*x);pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk);if(!eq){dd=1;break}}return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:Math.min(1,dd)}}
function folds(t,c,a,b){const w=(b-a)/5;return [...Array(5)].map((_,f)=>{const x=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:x.length,expectancy:mean(x.map(z=>z.gross-c))}})}
function nbrs(n){const c=C[n],o=[];for(const form of [150,180,210])for(const target of [.10,.12,.14])for(const hold of [150,180,210])o.push({...c,form,target,hold});return o}
const syms=await universe(),rows=new Map(),preps=new Map();for(const s of syms){try{const r=await kl(s);if(r.length>800){rows.set(s,r);preps.set(s,prep(r));console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}if(!rows.has('BTCUSDT')){const r=await kl('BTCUSDT');rows.set('BTCUSDT',r);preps.set('BTCUSDT',prep(r))}const br=rows.get('BTCUSDT'),cut=br[0].t+(br.at(-1).t-br[0].t)*(1-OOS),end=br.at(-1).t,res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round15.json',symbols:syms,usable:[...rows.keys()],cutoff:new Date(cut).toISOString(),reports:{},winners:[],verdict:'NO_STRATEGY_APPROVED'};
for(const n of Object.keys(C)){const all=sim(rows,preps,C[n]),oos=all.filter(x=>x.entryT>=cut),b=met(oos,BASE),s=met(oos,STRESS),wf=folds(oos,BASE,cut,end),pf=wf.filter(x=>x.n>0&&x.expectancy>0).length;let frac=0;if(b.n>=100&&b.pf>=1.15&&b.expectancy>0&&s.expectancy>0&&pf>=4&&b.maxDD<=.20){let pos=0,z=0;for(const q of nbrs(n)){const m=met(sim(rows,preps,q).filter(x=>x.entryT>=cut),BASE);pos+=(m.expectancy>0&&m.pf>1)?1:0;z++}frac=pos/z}const pass=b.n>=100&&b.pf>=1.15&&b.expectancy>0&&s.expectancy>0&&pf>=4&&b.maxDD<=.20&&frac>=.70;res.reports[n]={allTrades:all.length,oosBase:b,oosDoubleCost:s,folds:wf,positiveFolds:pf,neighborFraction:frac,pass};if(pass)res.winners.push(n)}res.verdict=res.winners.length?'PROCEED_TO_FINAL_HOLDOUT':'NO_STRATEGY_APPROVED';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round15-discovery.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
