import fs from 'node:fs/promises';
const API=['https://api-gcp.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com','https://data-api.binance.vision'];
const SYMS=['ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','SUIUSDT','ARBUSDT','OPUSDT','XLMUSDT','HBARUSDT','ICPUSDT','ETCUSDT','FILUSDT','ATOMUSDT'];
const DAYS=900,BASE=.0036,STRESS=.0072,ACCOUNT=20.08,RESERVE=2,HOLD=36,MAXPOS=1;
const MAJ=new Set(['ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT']);
async function get(p){let e;for(const b of API){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=1h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],q:+k[7],tb:+k[10],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;const med=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function prep(r){const c=r.map(x=>x.c),e20=ema(c,20),e50=ema(c,50),tr=[];for(let i=0;i<r.length;i++)tr.push(i?Math.max(r[i].h-r[i].l,Math.abs(r[i].h-r[i-1].c),Math.abs(r[i].l-r[i-1].c)):r[i].h-r[i].l);const atr=ema(tr,14),rsi=new Array(r.length).fill(NaN);for(let i=14;i<r.length;i++){let g=0,l=0;for(let j=i-13;j<=i;j++){const d=c[j]-c[j-1];if(d>0)g+=d;else l-=d}const ag=g/14,al=l/14;rsi[i]=al===0?100:100-(100/(1+ag/al))}return {e20,e50,atr,rsi}}
function maxPrev(r,i,n){let v=-Infinity;for(let j=i-n;j<i;j++)v=Math.max(v,r[j].h);return v}
function signal(r,p,i,opt){if(i<80)return null;const lane=MAJ.has(opt.sym)?'BIG':'SMALL',relMin=lane==='BIG'?opt.bigRel:opt.smallRel,takerMin=lane==='BIG'?opt.bigTaker:opt.smallTaker;const prior=r.slice(i-24,i),rv=med(prior.map(x=>x.q));const rel=rv? r[i].q/rv:0;const flow=r.slice(i-7,i+1),fq=flow.reduce((s,x)=>s+x.q,0),tk=fq?flow.reduce((s,x)=>s+x.tb,0)/fq:0;const resistance=maxPrev(r,i,20),atr=p.atr[i],rsi=p.rsi[i];if(!(r[i].c>resistance*1.001&&r[i].c>p.e20[i]&&p.e20[i]>p.e50[i]&&rel>=relMin&&tk>=takerMin&&rsi>=52&&rsi<=66&&atr>0))return null;const stop=r[i].c-1.05*atr,stopPct=(r[i].c-stop)/r[i].c;if(stopPct<=0||stopPct>(lane==='BIG'?.025:.022))return null;const riskCap=lane==='BIG'?.20:.10,maxPos=lane==='BIG'?7:5.5,notional=Math.min(maxPos,riskCap/stopPct,ACCOUNT-RESERVE);if(notional<5)return null;return {lane,rel,tk,rsi,atr,stopPct,notional,score:(lane==='BIG'?92:94)+Math.min(5,(rel-relMin)*4)+Math.min(3,(tk-takerMin)*30)}}
function trade(r,p,si){const en=r[si+1]?.o;if(!(en>0))return null;const lane=si._sig.lane,risk=Math.max(si._sig.atr*1.05,en*0.002),stop=en-risk,target=en+3.4*risk,last=Math.min(r.length-1,si+1+HOLD);let ex=r[last].c,why='TIME',xt=r[last].t;for(let j=si+1;j<=last;j++){if(r[j].o<=stop){ex=r[j].o;why='GAP_STOP';xt=r[j].t;break}if(r[j].l<=stop){ex=stop;why='STOP';xt=r[j].t;break}if(r[j].h>=target){ex=target;why='TARGET';xt=r[j].t;break}}return {entryT:r[si+1].t,exitT:xt,gross:ex/en-1,notional:si._sig.notional,lane,reason:why}}
function metrics(t,cost){const rs=t.map(z=>z.gross-cost),gp=rs.filter(x=>x>0).reduce((a,b)=>a+b,0),gl=Math.abs(rs.filter(x=>x<0).reduce((a,b)=>a+b,0));let eq=ACCOUNT,pk=eq,dd=0;for(let i=0;i<t.length;i++){eq+=t[i].notional*rs[i];pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}const profits=t.map((z,i)=>z.notional*rs[i]).filter(x=>x>0).sort((a,b)=>b-a),total=profits.reduce((a,b)=>a+b,0);return {n:rs.length,expectancy:mean(rs),pf:gl?gp/gl:(gp>0?999:0),winRate:rs.length?rs.filter(x=>x>0).length/rs.length:0,maxDD:dd,netPnLUSDT:eq-ACCOUNT,top2ProfitShare:total?profits.slice(0,2).reduce((a,b)=>a+b,0)/total:1}}
function folds(t,cost){if(!t.length)return Array.from({length:5},()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return Array.from({length:5},(_,f)=>{const q=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:q.length,expectancy:q.length?mean(q.map(z=>z.gross-cost)):0}})}
const rows=new Map(),ps=new Map();for(const s of ['BTCUSDT',...SYMS]){try{const r=await kl(s);if(r.length>500){rows.set(s,r);ps.set(s,prep(r));console.error('loaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}const br=rows.get('BTCUSDT'),bp=ps.get('BTCUSDT');if(!br)throw new Error('BTC missing');const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,i]))]));const cut=br[0].t+(br.at(-1).t-br[0].t)*.70,holdCut=br[0].t+(br.at(-1).t-br[0].t)*.85;
function run(opt){const tr=[];let occupied=0;for(let bi=80;bi<br.length-2;bi++){const tm=br[bi].t;if(tm<cut||tm<occupied)continue;if(!(br[bi].c>bp.e20[bi]&&bp.e20[bi]>bp.e50[bi]))continue;const cand=[];for(const s of SYMS){const r=rows.get(s),p=ps.get(s),i=maps.get(s)?.get(tm);if(i==null||i+2>=r.length)continue;const f=signal(r,p,i,{...opt,sym:s});if(f)cand.push({s,r,p,i,f})}cand.sort((a,b)=>b.f.score-a.f.score);const x=cand[0];if(!x)continue;x.i._sig=x.f;const holder=new Number(x.i);holder._sig=x.f;const z=trade(x.r,x.p,holder);if(z){tr.push({sym:x.s,score:x.f.score,...z});occupied=z.exitT}}return tr.sort((a,b)=>a.entryT-b.entryT)}
const baseOpt={bigRel:1.35,smallRel:1.40,bigTaker:.55,smallTaker:.57};const tr=run(baseOpt),base=metrics(tr,BASE),doubleCost=metrics(tr,STRESS),wf=folds(tr,BASE),positiveFolds=wf.filter(x=>x.n>0&&x.expectancy>0).length,holdout=metrics(tr.filter(x=>x.entryT>=holdCut),BASE);
const neighbors=[];for(const dr of [-.10,0,.10])for(const dt of [-.01,0,.01]){const o={bigRel:baseOpt.bigRel+dr,smallRel:baseOpt.smallRel+dr,bigTaker:baseOpt.bigTaker+dt,smallTaker:baseOpt.smallTaker+dt};const q=run(o),m=metrics(q,BASE);neighbors.push({params:o,n:m.n,expectancy:m.expectancy,pf:m.pf,positive:m.expectancy>0})}const robustShare=neighbors.filter(x=>x.positive).length/neighbors.length;
const discovery=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&doubleCost.expectancy>0&&positiveFolds>=4&&base.maxDD<=.20;const paperGate=base.n>=200&&base.pf>=1.20&&holdout.expectancy>0&&base.top2ProfitShare<=.50;const robustness=robustShare>=.70;const historicalPass=discovery&&paperGate&&robustness;
const out={generatedAt:new Date().toISOString(),strategy:'HARDENED_EDGE_WORKER_V1_HISTORICAL_PROXY',sourceWorker:'src/edge-worker.js',oosStart:new Date(cut).toISOString(),finalHoldoutStart:new Date(holdCut).toISOString(),symbols:SYMS,usable:[...rows.keys()],base,doubleCost,folds:wf,positiveFolds,finalHoldout:holdout,robustness:{positiveNeighborShare:robustShare,neighbors},gates:{discovery,paperGate,robustness,historicalPass},verdict:historicalPass?'HISTORICAL_GATE_PASS_FORWARD_PAPER_REQUIRED':'NO_LIVE_APPROVAL',authorization:'FORWARD_PAPER_ONLY',liveTrading:false,validatedStrategyRelease:null,sampleTrades:tr.slice(-10)};await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round25.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));