import fs from 'node:fs/promises';
const API=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const BAD=new Set(['USDC','FDUSD','TUSD','USDP','DAI','EUR','AEUR','TRY','BRL','BIDR','IDRT','UAH','NGN','RUB','GBP','AUD','BUSD','USD1','RLUSD','USDE','XUSD','EURI','XAUT','PAXG','WBTC','WETH']);
const HOLD=new Set(['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT']);
const DAYS=1825, BASE=.0036, STRESS=.0072, ACCOUNT=20.12, NOTIONAL=5.25, LIQ=1e7, AGE=2190;
const STOP=.03,TARGET=.12,HOLD_BARS=90,REB=42;
const IDS=['EMA20_100_TREND','EMA50_200_TREND','DONCHIAN20_BREAKOUT','DONCHIAN55_BREAKOUT','BB20_BREAKOUT','ATR_BREAKOUT','TSMOM30_EMA200','TSMOM90_EMA200','ADX_TREND','MACD_TREND','RSI_MEANREV_BULL','BB_MEANREV_BULL','ZSCORE60_MEANREV','CRASH_RECLAIM','VOLUME_BREAKOUT','LOWVOL_MOM','XSMOM30','RISK_ADJ_MOM','VOL_CONTRACTION_BREAKOUT','DUAL_TREND_MOM'];
async function get(p){let e;for(const b of API){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function universe(){const ex=await get('/api/v3/exchangeInfo'),tk=await get('/api/v3/ticker/24hr'),m=new Map(ex.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed).map(x=>[x.symbol,x]));return tk.filter(x=>m.has(x.symbol)&&!HOLD.has(x.symbol)).filter(x=>{const b=m.get(x.symbol).baseAsset;return !BAD.has(b)&&!/(UP|DOWN|BULL|BEAR)$/.test(b)}).map(x=>({s:x.symbol,q:+x.quoteVolume})).filter(x=>x.q>0).sort((a,b)=>b.q-a.q).slice(0,30).map(x=>x.s)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],v:+k[5],q:+k[7],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN;const sd=a=>{const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))};
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function sma(v,p){const o=new Array(v.length).fill(NaN);let s=0;for(let i=0;i<v.length;i++){s+=v[i];if(i>=p)s-=v[i-p];if(i>=p-1)o[i]=s/p}return o}
function rsi(v,p=14){const o=new Array(v.length).fill(NaN);let ag=0,al=0;for(let i=1;i<=p&&i<v.length;i++){const d=v[i]-v[i-1];ag+=Math.max(d,0);al+=Math.max(-d,0)}if(v.length>p){ag/=p;al/=p;o[p]=al===0?100:100-100/(1+ag/al)}for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;o[i]=al===0?100:100-100/(1+ag/al)}return o}
function atr(r,p=14){const tr=r.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-r[i-1].c),Math.abs(x.l-r[i-1].c)):x.h-x.l);return ema(tr,p)}
function adx(r,p=14){const n=r.length,trs=[],pd=[],md=[];for(let i=0;i<n;i++){if(!i){trs.push(r[i].h-r[i].l);pd.push(0);md.push(0);continue}trs.push(Math.max(r[i].h-r[i].l,Math.abs(r[i].h-r[i-1].c),Math.abs(r[i].l-r[i-1].c)));const up=r[i].h-r[i-1].h,dn=r[i-1].l-r[i].l;pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}const a=ema(trs,p),ap=ema(pd,p),am=ema(md,p),pdi=a.map((x,i)=>x?100*ap[i]/x:NaN),mdi=a.map((x,i)=>x?100*am[i]/x:NaN),dx=pdi.map((x,i)=>(x+mdi[i])?100*Math.abs(x-mdi[i])/(x+mdi[i]):NaN);return {adx:ema(dx.map(x=>Number.isFinite(x)?x:0),p),pdi,mdi}}
function prep(r){const c=r.map(x=>x.c),v=r.map(x=>x.v),e20=ema(c,20),e50=ema(c,50),e100=ema(c,100),e200=ema(c,200),a14=atr(r),rs=rsi(c),m12=ema(c,12),m26=ema(c,26),mac=m12.map((x,i)=>x-m26[i]),sig=ema(mac.map(x=>Number.isFinite(x)?x:0),9),s20=sma(c,20),vol20=sma(v,20),{adx:ax,pdi,mdi}=adx(r);const adv=new Array(r.length).fill(NaN),bbU=[],bbL=[],bbW=[],z60=[],rv180=[],atrMed60=[];for(let i=0;i<r.length;i++){if(i>=179)adv[i]=r.slice(i-179,i+1).reduce((s,x)=>s+x.q,0)/30;if(i>=19){const z=c.slice(i-19,i+1),d=sd(z);bbU[i]=mean(z)+2*d;bbL[i]=mean(z)-2*d;bbW[i]=d?4*d/mean(z):0}if(i>=59){const z=c.slice(i-59,i+1),d=sd(z);z60[i]=d?(c[i]-mean(z))/d:0;const av=a14.slice(i-59,i+1).filter(Number.isFinite).sort((a,b)=>a-b);atrMed60[i]=av.length?av[Math.floor(av.length/2)]:NaN}if(i>=180){const rr=[];for(let j=i-179;j<=i;j++)rr.push(c[j]/c[j-1]-1);rv180[i]=sd(rr)}}return {c,v,e20,e50,e100,e200,a14,rs,mac,sig,s20,vol20,ax,pdi,mdi,adv,bbU,bbL,bbW,z60,rv180,atrMed60}}
function hi(r,i,n){if(i<n)return NaN;let h=-Infinity;for(let j=i-n;j<i;j++)h=Math.max(h,r[j].h);return h}
function exitTrade(r,ei){const en=r[ei].o,st=en*(1-STOP),tg=en*(1+TARGET),last=Math.min(r.length-1,ei+HOLD_BARS);let ex=r[last].c,xt=r[last].t,why='TIME';for(let j=ei;j<=last;j++){if(r[j].l<=st){ex=st;xt=r[j].t;why='STOP';break}if(r[j].h>=tg){ex=tg;xt=r[j].t;why='TARGET';break}}return {entryT:r[ei].t,exitT:xt,gross:ex/en-1,reason:why}}
function regime(br,bp,i){return i>=180&&br[i].c>bp.e200[i]&&br[i].c/br[i-180].c-1>0}
function perSignal(id,r,p,i,br,bp,bi){if(i<AGE||p.adv[i]<LIQ)return false;const c=r[i].c;switch(id){case'EMA20_100_TREND':return c>p.e100[i]&&p.e20[i]>p.e100[i];case'EMA50_200_TREND':return c>p.e200[i]&&p.e50[i]>p.e200[i];case'DONCHIAN20_BREAKOUT':return c>hi(r,i,20);case'DONCHIAN55_BREAKOUT':return c>hi(r,i,55);case'BB20_BREAKOUT':return c>p.bbU[i];case'ATR_BREAKOUT':return c>hi(r,i,20)&&p.a14[i]/c>p.atrMed60[i]/c;case'TSMOM30_EMA200':return i>=180&&c/r[i-180].c-1>0&&c>p.e200[i];case'TSMOM90_EMA200':return i>=540&&c/r[i-540].c-1>0&&c>p.e200[i];case'ADX_TREND':return p.ax[i]>25&&p.pdi[i]>p.mdi[i]&&c>p.e100[i];case'MACD_TREND':return p.mac[i]>p.sig[i]&&c>p.e200[i];case'RSI_MEANREV_BULL':return p.rs[i]<30&&c>p.e200[i];case'BB_MEANREV_BULL':return c<p.bbL[i]&&c>p.e200[i];case'ZSCORE60_MEANREV':return p.z60[i]<-2&&c>p.e200[i];case'CRASH_RECLAIM':return i>=7&&c/r[i-6].c-1<-.08&&c>r[i-1].h&&regime(br,bp,bi);case'VOLUME_BREAKOUT':return c>hi(r,i,20)&&r[i].v>2*p.vol20[i];case'VOL_CONTRACTION_BREAKOUT':{if(i<120)return false;const ws=p.bbW.slice(i-119,i+1).filter(Number.isFinite).sort((a,b)=>a-b),thr=ws[Math.floor(ws.length*.2)];return p.bbW[i]<=thr&&c>hi(r,i,20)}case'DUAL_TREND_MOM':return i>=180&&p.e50[i]>p.e200[i]&&c>p.e200[i]&&c/r[i-180].c-1>0&&regime(br,bp,bi);default:return false}}
function met(t,cost){const x=t.map(z=>z.gross-cost),w=x.filter(v=>v>0),l=x.filter(v=>v<0),gp=w.reduce((s,v)=>s+v,0),gl=Math.abs(l.reduce((s,v)=>s+v,0));let eq=ACCOUNT,pk=eq,dd=0;for(const v of x){eq=Math.max(0,eq+NOTIONAL*v);pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}return {n:x.length,expectancy:x.length?mean(x):0,pf:gl?gp/gl:(gp>0?999:0),winRate:x.length?w.length/x.length:0,maxDD:dd,grossProfit:gp,grossLoss:gl}}
function folds(t,cost){if(!t.length)return Array.from({length:5},()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return Array.from({length:5},(_,f)=>{const q=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:q.length,expectancy:q.length?mean(q.map(z=>z.gross-cost)):0}})}
const syms=await universe();const rows=new Map(),ps=new Map();for(const s of [...new Set(['BTCUSDT',...syms])]){try{const r=await kl(s);if(r.length>AGE+200){rows.set(s,r);ps.set(s,prep(r));console.error('loaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}
const br=rows.get('BTCUSDT'),bp=ps.get('BTCUSDT');if(!br)throw new Error('BTC data missing');const cut=br[0].t+(br.at(-1).t-br[0].t)*.70;const bmap=new Map(br.map((x,i)=>[x.t,i]));const out={generatedAt:new Date().toISOString(),protocol:'validation/evidence-gate-round18.json',universe:syms,usable:[...rows.keys()],oosCut:new Date(cut).toISOString(),results:[],promotable:[],verdict:'NO_STRATEGY_APPROVED'};
for(const id of IDS){let tr=[];if(['LOWVOL_MOM','XSMOM30','RISK_ADJ_MOM'].includes(id)){for(let bi=AGE;bi<br.length-1;bi++){if(br[bi].t<cut||bi%REB!==0||!regime(br,bp,bi))continue;const cand=[];for(const [s,r] of rows){if(s==='BTCUSDT')continue;const mi=new Map(r.map((x,i)=>[x.t,i])),i=mi.get(br[bi].t);if(i==null||i<AGE||ps.get(s).adv[i]<LIQ||i<180)continue;const mom=r[i].c/r[i-180].c-1,vol=ps.get(s).rv180[i];if(!Number.isFinite(vol)||vol<=0)continue;cand.push({s,r,i,mom,vol})}let pick=[];if(id==='XSMOM30')pick=cand.filter(x=>x.mom>0).sort((a,b)=>b.mom-a.mom).slice(0,2);if(id==='RISK_ADJ_MOM')pick=cand.filter(x=>x.mom>0).sort((a,b)=>(b.mom/b.vol)-(a.mom/a.vol)).slice(0,2);if(id==='LOWVOL_MOM'){const q=[...cand].sort((a,b)=>a.vol-b.vol).slice(0,Math.max(2,Math.ceil(cand.length*.25)));pick=q.filter(x=>x.mom>0).sort((a,b)=>b.mom-a.mom).slice(0,2)}for(const x of pick)if(x.i+1<x.r.length)tr.push({sym:x.s,...exitTrade(x.r,x.i+1)})}}else{for(const [s,r] of rows){if(s==='BTCUSDT')continue;const p=ps.get(s);let busy=0;for(let i=AGE;i<r.length-1;i++){if(r[i].t<cut||r[i].t<busy)continue;const bi=bmap.get(r[i].t);if(bi==null)continue;if(perSignal(id,r,p,i,br,bp,bi)){const z=exitTrade(r,i+1);tr.push({sym:s,...z});busy=z.exitT}}}}
tr.sort((a,b)=>a.entryT-b.entryT);const base=met(tr,BASE),stress=met(tr,STRESS),wf=folds(tr,BASE),pos=wf.filter(x=>x.n>0&&x.expectancy>0).length,pass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&stress.expectancy>0&&pos>=4&&base.maxDD<=.20;out.results.push({id,base,doubleCost:stress,folds:wf,positiveFolds:pos,pass});if(pass)out.promotable.push(id)}
out.results.sort((a,b)=>(b.pass-a.pass)||(b.doubleCost.pf-a.doubleCost.pf)||(b.base.pf-a.base.pf)||(b.base.n-a.base.n));if(out.promotable.length)out.verdict='PROMOTABLE_STRATEGIES_FOUND';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round18-tournament.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
