import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const SYMBOLS=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','LINKUSDT','LTCUSDT','BCHUSDT'];
const DAYS=1825,OOS=.30,BASE=.003,STRESS=.006,ACCOUNT=20.12,ORDER=7;
const G={minN:100,minPF:1.15,minFolds:4,maxDD:.20,minNbr:.70};
const CFG={
 RSI_RECLAIM_TREND:{oversold:35,reclaim:40,lookbackBars:3,stopAtr:1.5,targetAtr:3,maxHoldBars:30},
 BB_RECLAIM_TREND:{bbPeriod:20,bbStd:2,touchLookbackBars:2,stopAtr:1.5,targetAtr:2.5,maxHoldBars:30},
 SHOCK_RECLAIM_TREND:{shockBars:3,shockReturnMax:-.04,stopAtr:1.75,targetAtr:3.5,maxHoldBars:36}
};
async function get(p){let last;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();last=`${b}:${r.status}`}catch(e){last=e.message}}throw new Error(last||p)}
async function klines(s){const out=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)out.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],v:+k[5],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return out.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function atr(r,p=14){const tr=r.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-r[i-1].c),Math.abs(x.l-r[i-1].c)):x.h-x.l);return ema(tr,p)}
function rsi(r,p=14){const o=new Array(r.length).fill(NaN);if(r.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=r[i].c-r[i-1].c;if(d>=0)g+=d;else l-=d}g/=p;l/=p;o[p]=l===0?100:100-100/(1+g/l);for(let i=p+1;i<r.length;i++){const d=r[i].c-r[i-1].c;g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;o[i]=l===0?100:100-100/(1+g/l)}return o}
function prep(r){const c=r.map(x=>x.c),e50=ema(c,50),e200=ema(c,200),a=atr(r,14),rs=rsi(r,14),sma20=c.map((_,i)=>i>=19?mean(c.slice(i-19,i+1)):NaN),sd20=c.map((_,i)=>i>=19?sd(c.slice(i-19,i+1)):NaN);return {c,e50,e200,a,rs,sma20,sd20}}
function regime(p,r,i){return r[i].c>p.e200[i]&&p.e50[i]>p.e200[i]&&p.e50[i]>p.e50[i-6]}
function sig(name,r,p,i,c){if(i<220||!regime(p,r,i))return false;if(name==='RSI_RECLAIM_TREND'){const dipped=p.rs.slice(i-c.lookbackBars,i).some(x=>Number.isFinite(x)&&x<c.oversold);return dipped&&p.rs[i]>=c.reclaim&&r[i].c>r[i-1].h}if(name==='BB_RECLAIM_TREND'){let touch=false;for(let j=Math.max(20,i-c.touchLookbackBars);j<i;j++){const lb=p.sma20[j]-c.bbStd*p.sd20[j];if(r[j].l<=lb)touch=true}const lb=p.sma20[i]-c.bbStd*p.sd20[i];return touch&&r[i].c>lb&&r[i].c>r[i-1].c}if(name==='SHOCK_RECLAIM_TREND'){const shock=r[i-1].c/r[i-1-c.shockBars].c-1;return shock<=c.shockReturnMax&&r[i].c>r[i].o&&r[i].c>r[i-1].h}return false}
function sim(name,r,c){const p=prep(r),tr=[];let pos=null;for(let i=220;i<r.length-1;i++){if(pos){const b=r[i];if(b.l<=pos.stop){tr.push({t:b.t,gross:pos.stop/pos.entry-1});pos=null;continue}if(b.h>=pos.target){tr.push({t:b.t,gross:pos.target/pos.entry-1});pos=null;continue}pos.held++;if(b.c<p.e50[i]||pos.held>=c.maxHoldBars){tr.push({t:b.t,gross:b.c/pos.entry-1});pos=null;continue}}if(!pos&&sig(name,r,p,i,c)){const en=r[i+1].o,aa=p.a[i];if(en>0&&aa>0)pos={entry:en,stop:en-c.stopAtr*aa,target:en+c.targetAtr*aa,held:0}}}return tr}
function dd(rets){let eq=ACCOUNT,pk=ACCOUNT,m=0;for(const x of rets){eq+=ORDER*x;pk=Math.max(pk,eq);if(eq<=0)return 1;m=Math.max(m,1-eq/pk)}return m}
function met(tr,cost){const r=tr.map(x=>x.gross-cost),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0)),ps=[...w].sort((a,b)=>b-a);return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:dd(r),top2Share:gp?ps.slice(0,2).reduce((s,x)=>s+x,0)/gp:0}}
function folds(tr,cost,start,end){const w=(end-start)/5,o=[];for(let f=0;f<5;f++){const a=start+f*w,b=f===4?end+1:start+(f+1)*w,t=tr.filter(x=>x.t>=a&&x.t<b);o.push({n:t.length,expectancy:mean(t.map(x=>x.gross-cost))})}return o}
function neighbors(name){const out=[];if(name==='RSI_RECLAIM_TREND')for(const a of [32,35,38])for(const s of [1.25,1.5,1.75])for(const t of [2.5,3,3.5])out.push({...CFG[name],oversold:a,stopAtr:s,targetAtr:t});if(name==='BB_RECLAIM_TREND')for(const a of [1.8,2,2.2])for(const s of [1.25,1.5,1.75])for(const t of [2.25,2.5,2.75])out.push({...CFG[name],bbStd:a,stopAtr:s,targetAtr:t});if(name==='SHOCK_RECLAIM_TREND')for(const a of [-.03,-.04,-.05])for(const s of [1.5,1.75,2])for(const t of [3,3.5,4])out.push({...CFG[name],shockReturnMax:a,stopAtr:s,targetAtr:t});return out}
const rows=new Map();for(const s of SYMBOLS){try{const r=await klines(s);if(r.length>1000){rows.set(s,r);console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}
const minT=Math.min(...[...rows.values()].map(r=>r[0].t)),maxT=Math.max(...[...rows.values()].map(r=>r.at(-1).t)),cut=minT+(maxT-minT)*(1-OOS);const res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round6.json',cutoff:new Date(cut).toISOString(),reports:{}};
for(const name of Object.keys(CFG)){const all=[];for(const [sym,r] of rows)for(const t of sim(name,r,CFG[name]))all.push({...t,sym});all.sort((a,b)=>a.t-b.t);const oos=all.filter(x=>x.t>=cut),base=met(oos,BASE),stress=met(oos,STRESS),fs=folds(oos,BASE,cut,maxT),pfolds=fs.filter(x=>x.n>0&&x.expectancy>0).length;let pos=0,n=0,nbr=[];for(const c of neighbors(name)){const nt=[];for(const r of rows.values())for(const t of sim(name,r,c))if(t.t>=cut)nt.push(t);const m=met(nt,BASE),ok=m.expectancy>0&&m.pf>1;pos+=ok?1:0;n++;nbr.push({n:m.n,expectancy:m.expectancy,pf:m.pf,ok})}const frac=pos/n,pass=base.n>=G.minN&&base.pf>=G.minPF&&base.expectancy>0&&stress.expectancy>0&&pfolds>=G.minFolds&&base.maxDD<=G.maxDD&&frac>=G.minNbr;res.reports[name]={allTrades:all.length,oosBase:base,oosDoubleCost:stress,folds:fs,positiveFolds:pfolds,neighborFraction:frac,discoveryPass:pass}}
res.discoveryWinners=Object.entries(res.reports).filter(([,v])=>v.discoveryPass).map(([k])=>k);res.verdict=res.discoveryWinners.length?'PROCEED_TO_UNTOUCHED_SYMBOL_HOLDOUT':'NO_STRATEGY_APPROVED';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round6-discovery.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
