import fs from 'node:fs/promises';
const API=['https://api.binance.com','https://api-gcp.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com','https://data-api.binance.vision'];
const SYMS=['ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','SUIUSDT','ARBUSDT','OPUSDT','XLMUSDT','HBARUSDT','ICPUSDT','ETCUSDT','FILUSDT','ATOMUSDT'];
const DAYS=900,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,RESERVE=2,MAXRISK=.20,ATRM=2.5,HOLD=120,MAXPOS=2;
async function get(p){let e;for(const b of API){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=1h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],q:+k[7],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function prep(r){const c=r.map(x=>x.c),tr=[],plus=[],minus=[];for(let i=0;i<r.length;i++){if(!i){tr.push(r[i].h-r[i].l);plus.push(0);minus.push(0);continue}const up=r[i].h-r[i-1].h,dn=r[i-1].l-r[i].l;tr.push(Math.max(r[i].h-r[i].l,Math.abs(r[i].h-r[i-1].c),Math.abs(r[i].l-r[i-1].c)));plus.push(up>dn&&up>0?up:0);minus.push(dn>up&&dn>0?dn:0)}const a=ema(tr,14),ap=ema(plus,14),am=ema(minus,14),dx=new Array(r.length).fill(NaN);for(let i=0;i<r.length;i++)if(a[i]>0){const p=100*ap[i]/a[i],m=100*am[i]/a[i],d=p+m;dx[i]=d?100*Math.abs(p-m)/d:0}const clean=dx.map(x=>Number.isFinite(x)?x:0),adx=ema(clean.slice(13),14);const ax=new Array(r.length).fill(NaN);for(let j=0;j<adx.length;j++)if(Number.isFinite(adx[j]))ax[j+13]=adx[j];return {e50:ema(c,50),e200:ema(c,200),atr:a,adx:ax}}
function maxPrev(r,i,n,key){let v=-Infinity;for(let j=i-n;j<i;j++)v=Math.max(v,r[j][key]);return v}function minPrev(r,i,n,key){let v=Infinity;for(let j=i-n;j<i;j++)v=Math.min(v,r[j][key]);return v}
function signal(r,p,i){if(i<220)return null;const dc=maxPrev(r,i,20,'h'),qavg=mean(r.slice(i-19,i+1).map(x=>x.q)),rv=qavg?r[i].q/qavg:0,atr=p.atr[i];if(!(r[i].c>dc&&p.e50[i]>p.e200[i]&&r[i].c>p.e200[i]&&p.adx[i]>=20&&rv>=1.20&&atr>0))return null;const strength=(r[i].c-dc)/atr;return {rv,adx:p.adx[i],strength,score:p.adx[i]+10*Math.min(3,strength)+3*Math.min(3,rv)}}
function exit(r,p,ei){const en=r[ei]?.o,a0=p.atr[ei-1];if(!(en>0&&a0>0))return null;let stop=en-ATRM*a0,high=en,last=Math.min(r.length-1,ei+HOLD),ex=r[last].c,xt=r[last].t,why='TIME';for(let j=ei;j<=last;j++){if(r[j].o<stop){ex=r[j].o;xt=r[j].t;why='GAP_STOP';break}if(r[j].l<=stop){ex=stop;xt=r[j].t;why='ATR_TRAIL';break}if(j>=ei+10){const low10=minPrev(r,j,10,'l');if(r[j].c<low10){ex=r[j].c;xt=r[j].t;why='DONCHIAN10';break}}high=Math.max(high,r[j].h);if(Number.isFinite(p.atr[j]))stop=Math.max(stop,high-ATRM*p.atr[j])}const frac=Math.max(.0001,ATRM*a0/en),notional=Math.min(ORDER,MAXRISK/frac,ACCOUNT-RESERVE);return {entryT:r[ei].t,exitT:xt,gross:ex/en-1,notional,reason:why}}
function metrics(t,cost){const rs=t.map(z=>z.gross-cost),gp=rs.filter(x=>x>0).reduce((a,b)=>a+b,0),gl=Math.abs(rs.filter(x=>x<0).reduce((a,b)=>a+b,0));let eq=ACCOUNT,pk=eq,dd=0;for(let i=0;i<t.length;i++){eq+=t[i].notional*rs[i];pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}return {n:rs.length,expectancy:mean(rs),pf:gl?gp/gl:(gp>0?999:0),winRate:rs.length?rs.filter(x=>x>0).length/rs.length:0,maxDD:dd,netPnLUSDT:eq-ACCOUNT}}
function folds(t,cost){if(!t.length)return Array.from({length:5},()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return Array.from({length:5},(_,f)=>{const q=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:q.length,expectancy:q.length?mean(q.map(z=>z.gross-cost)):0}})}
const rows=new Map(),ps=new Map();for(const s of ['BTCUSDT',...SYMS]){try{const r=await kl(s);if(r.length>500){rows.set(s,r);ps.set(s,prep(r));console.error('loaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}const br=rows.get('BTCUSDT'),bp=ps.get('BTCUSDT');if(!br)throw new Error('BTC missing');const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,i]))]));const cut=br[0].t+(br.at(-1).t-br[0].t)*.70,tr=[];let occupied=[];
for(let bi=220;bi<br.length-1;bi++){if(br[bi].t<cut)continue;occupied=occupied.filter(x=>x>br[bi].t);if(occupied.length>=MAXPOS)continue;if(!(br[bi].c>bp.e200[bi]&&bp.e50[bi]>bp.e200[bi]))continue;const cand=[];for(const s of SYMS){const r=rows.get(s),p=ps.get(s),i=maps.get(s)?.get(br[bi].t);if(i==null||i+1>=r.length)continue;const f=signal(r,p,i);if(f)cand.push({s,r,p,i,...f})}cand.sort((a,b)=>b.score-a.score);for(const x of cand.slice(0,MAXPOS-occupied.length)){const z=exit(x.r,x.p,x.i+1);if(z){tr.push({sym:x.s,score:x.score,adx:x.adx,relativeVolume:x.rv,...z});occupied.push(z.exitT)}}}
tr.sort((a,b)=>a.entryT-b.entryT);const base=metrics(tr,BASE),doubleCost=metrics(tr,STRESS),wf=folds(tr,BASE),positiveFolds=wf.filter(x=>x.n>0&&x.expectancy>0).length;const pass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&doubleCost.expectancy>0&&positiveFolds>=4&&base.maxDD<=.20;const out={generatedAt:new Date().toISOString(),protocol:'validation/evidence-gate-round24.json',strategy:'COMMUNITY_TREND_BREAKOUT_V1',inspiration:'Donchian breakout + moving-average trend filter + ADX + volume confirmation + trailing exit',symbols:SYMS,usable:[...rows.keys()],oosCut:new Date(cut).toISOString(),base,doubleCost,folds:wf,positiveFolds,pass,verdict:pass?'DISCOVERY_GATE_PASS_FORWARD_PAPER_ONLY':'NO_DISCOVERY_PASS',liveTrading:false,validatedStrategyRelease:null,sampleTrades:tr.slice(-10)};await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round24.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
