import fs from 'node:fs/promises';
const API=['https://api.binance.com','https://api-gcp.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com','https://data-api.binance.vision'];
const SYMS=['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT','NEARUSDT','FILUSDT','ARBUSDT','SUIUSDT','ENAUSDT','AAVEUSDT','LINKUSDT','DOTUSDT','ATOMUSDT','UNIUSDT','ETCUSDT','LTCUSDT'];
const DAYS=1825,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,RESERVE=2,MAXRISK=.20,AGE=800,REB=42,HOLD=120,ATRM=2.5;
async function get(p){let e;for(const b of API){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function atr(r,p=14){const tr=r.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-r[i-1].c),Math.abs(x.l-r[i-1].c)):x.h-x.l);return ema(tr,p)}
function prep(r){const c=r.map(x=>x.c);return {e50:ema(c,50),e200:ema(c,200),a14:atr(r)}}
function exit(r,p,ei){const en=r[ei]?.o,a0=p.a14[ei-1];if(!(en>0&&a0>0))return null;let stop=en-ATRM*a0,high=en,last=Math.min(r.length-1,ei+HOLD),ex=r[last].c,xt=r[last].t,why='TIME';for(let j=ei;j<=last;j++){if(r[j].o<stop){ex=r[j].o;xt=r[j].t;why='GAP_STOP';break}if(r[j].l<=stop){ex=stop;xt=r[j].t;why='TRAIL_STOP';break}if(j>ei&&Number.isFinite(p.e50[j-1])&&r[j-1].c<p.e50[j-1]){ex=r[j].o;xt=r[j].t;why='EMA50_EXIT';break}high=Math.max(high,r[j].c);if(Number.isFinite(p.a14[j]))stop=Math.max(stop,high-ATRM*p.a14[j])}const frac=Math.max(.0001,ATRM*a0/en),notional=Math.min(ORDER,MAXRISK/frac,ACCOUNT-RESERVE);return {entryT:r[ei].t,exitT:xt,gross:ex/en-1,reason:why,notional}}
function metrics(t,cost){const rs=t.map(z=>z.gross-cost),gp=rs.filter(x=>x>0).reduce((a,b)=>a+b,0),gl=Math.abs(rs.filter(x=>x<0).reduce((a,b)=>a+b,0));let eq=ACCOUNT,pk=eq,dd=0;for(let i=0;i<t.length;i++){eq+=t[i].notional*rs[i];pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}return {n:rs.length,expectancy:mean(rs),pf:gl?gp/gl:(gp>0?999:0),winRate:rs.length?rs.filter(x=>x>0).length/rs.length:0,maxDD:dd,netPnLUSDT:eq-ACCOUNT}}
function folds(t,cost){if(!t.length)return Array.from({length:5},()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return Array.from({length:5},(_,f)=>{const q=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:q.length,expectancy:q.length?mean(q.map(z=>z.gross-cost)):0}})}
const rows=new Map(),ps=new Map();for(const s of ['BTCUSDT',...SYMS]){try{const r=await kl(s);if(r.length>AGE+550){rows.set(s,r);ps.set(s,prep(r));console.error('loaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}
const br=rows.get('BTCUSDT'),bp=ps.get('BTCUSDT');if(!br)throw new Error('BTC missing');const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,i]))]));const cut=br[0].t+(br.at(-1).t-br[0].t)*.70,tr=[];
for(let bi=AGE;bi<br.length-1;bi++){if(br[bi].t<cut||bi%REB!==0)continue;if(!(br[bi].c>bp.e200[bi]&&br[bi].c/br[bi-180].c-1>0))continue;const cand=[];for(const s of SYMS){const r=rows.get(s),p=ps.get(s),i=maps.get(s)?.get(br[bi].t);if(i==null||i<AGE||i<540||i+1>=r.length)continue;const m30=r[i].c/r[i-180].c-1,m90=r[i].c/r[i-540].c-1,trend=r[i].c/p.e200[i]-1;if(m30>0&&m90>0&&trend>0)cand.push({s,r,p,i,score:m30+m90})}cand.sort((a,b)=>b.score-a.score);for(const x of cand.slice(0,2)){const z=exit(x.r,x.p,x.i+1);if(z)tr.push({sym:x.s,...z})}}
tr.sort((a,b)=>a.entryT-b.entryT);const base=metrics(tr,BASE),stress=metrics(tr,STRESS),wf=folds(tr,BASE),positiveFolds=wf.filter(x=>x.n>0&&x.expectancy>0).length;const pass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&stress.expectancy>0&&positiveFolds>=4&&base.maxDD<=.20;
const out={generatedAt:new Date().toISOString(),protocol:'validation/evidence-gate-round22.json',strategy:'DUAL_HORIZON_MOM',symbols:SYMS,usable:[...rows.keys()],oosCut:new Date(cut).toISOString(),base,doubleCost:stress,folds:wf,positiveFolds,pass,verdict:pass?'DISCOVERY_GATE_PASS_FORWARD_PAPER_ONLY':'NO_DISCOVERY_PASS',liveTrading:false,validatedStrategyRelease:null,sampleTrades:tr.slice(-10)};
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round22.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
