import fs from 'node:fs/promises';

const API=['https://api-gcp.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com','https://data-api.binance.vision'];
const SYMS=['ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','SUIUSDT','ARBUSDT','OPUSDT','XLMUSDT','HBARUSDT'];
const MAJ=new Set(['ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT']);
const DAYS=420, BASE=.0036, STRESS=.0072, ACCOUNT=20.08, RESERVE=2, HOLD_BARS=144, MAXPOS=1;

async function get(path){let err;for(const b of API){try{const r=await fetch(b+path,{signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();err=`${b}:${r.status}`}catch(e){err=e.message}}throw new Error(err||path)}
async function kl15(s){const out=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=15m&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)out.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],q:+k[7],tb:+k[10],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return out.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
function emaSeries(v,p){const o=new Array(v.length).fill(NaN);if(!v.length)return o;let e=v[0],a=2/(p+1);o[0]=e;for(let i=1;i<v.length;i++){e=v[i]*a+e*(1-a);o[i]=e}return o}
function atrSeries(r,p=14){const tr=[];for(let i=0;i<r.length;i++){if(!i)tr.push(r[i].h-r[i].l);else tr.push(Math.max(r[i].h-r[i].l,Math.abs(r[i].h-r[i-1].c),Math.abs(r[i].l-r[i-1].c)))}const o=new Array(r.length).fill(NaN);for(let i=p;i<r.length;i++)o[i]=mean(tr.slice(i-p+1,i+1));return o}
function rsiAt(c,i){if(i<14)return 50;let g=0,l=0;for(let j=i-13;j<=i;j++){const d=c[j]-c[j-1];if(d>0)g+=d;else l-=d}if(l===0)return 100;const rs=(g/14)/(l/14);return 100-100/(1+rs)}
function aggregate(r,mins){const ms=mins*60_000,m=new Map();for(const x of r){const k=Math.floor(x.t/ms)*ms;let z=m.get(k);if(!z){z={t:k,o:x.o,h:x.h,l:x.l,c:x.c,q:0,tb:0,ct:k+ms-1};m.set(k,z)}z.h=Math.max(z.h,x.h);z.l=Math.min(z.l,x.l);z.c=x.c;z.q+=x.q;z.tb+=x.tb}return [...m.values()].sort((a,b)=>a.t-b.t)}
function prep(r){const c=r.map(x=>x.c);return {e20:emaSeries(c,20),e50:emaSeries(c,50),atr:atrSeries(r),c}}
function latestIndexAt(r,t){let lo=0,hi=r.length-1,ans=-1;while(lo<=hi){const mid=(lo+hi)>>1;if(r[mid].ct<=t){ans=mid;lo=mid+1}else hi=mid-1}return ans}
function detectSetup(r,p,i){if(i<25)return null;const last=r[i],e20=p.e20[i];for(let k=Math.max(22,i-4);k<i;k++){const prior=r.slice(k-20,k),res=Math.max(...prior.map(x=>x.h)),vmed=median(prior.map(x=>x.q)),b=r[k];if(b.c>res*1.001&&b.q>=vmed*1.25){const after=r.slice(k+1,i+1),held=after.every(x=>x.c>=res*0.997),retested=after.some(x=>x.l<=res*1.004);if(held&&retested&&last.c>=res)return {type:'BREAKOUT_RETEST',swingLow:Math.min(b.l,...after.map(x=>x.l))}}}
const pull=r.slice(i-2,i+1),touched=pull.some(x=>x.l<=e20*1.003&&x.l>=e20*0.985),recovered=last.c>e20&&last.c>last.o&&last.c>=r[i-1].c*0.998;if(touched&&recovered)return {type:'TREND_PULLBACK',swingLow:Math.min(...pull.map(x=>x.l))};return null}
function btcAllowed(b1,p1,i1,b4,p4,i4){if(i1<55||i4<55)return false;return b1[i1].c>p1.e50[i1]&&b4[i4].c>p4.e50[i4]&&p1.e20[i1]>=p1.e50[i1]*0.995&&p4.e20[i4]>=p4.e50[i4]*0.99}
function signal(r,p,i,h1,p1,h4,p4,b1,bp1,b4,bp4,opt){if(i<80)return null;const t=r[i].ct,i1=latestIndexAt(h1,t),i4=latestIndexAt(h4,t),bi1=latestIndexAt(b1,t),bi4=latestIndexAt(b4,t);if(i1<55||i4<55||bi1<55||bi4<55)return null;if(!btcAllowed(b1,bp1,bi1,b4,bp4,bi4))return null;const trend15=r[i].c>p.e20[i]&&p.e20[i]>p.e50[i],trend1=h1[i1].c>p1.e20[i1]&&p1.e20[i1]>p1.e50[i1],trend4=h4[i4].c>p4.e20[i4]&&p4.e20[i4]>p4.e50[i4];if(!(trend15&&trend1&&trend4))return null;const setup=detectSetup(r,p,i);if(!setup)return null;const lane=MAJ.has(opt.sym)?'BIG':'SMALL',relMin=lane==='BIG'?opt.bigRel:opt.smallRel,takerMin=lane==='BIG'?opt.bigTaker:opt.smallTaker;const relBase=median(r.slice(i-24,i).map(x=>x.q)),rel=relBase?r[i].q/relBase:0;const flow=r.slice(i-7,i+1),fq=flow.reduce((s,x)=>s+x.q,0),tk=fq?flow.reduce((s,x)=>s+x.tb,0)/fq:0,rsi=rsiAt(p.c,i),atr=p.atr[i];if(!(rel>=relMin&&tk>=takerMin&&rsi>=52&&rsi<=67&&atr>0))return null;const entry=r[i].c,stopRaw=Math.min(setup.swingLow*.998,entry-1.05*atr),risk=entry-stopRaw,stopPct=risk/entry,maxStop=lane==='BIG'?.025:.022;if(!(risk>0&&stopPct<=maxStop))return null;const riskCap=lane==='BIG'?.20:.10,maxPos=lane==='BIG'?7:5.5,notional=Math.min(maxPos,riskCap/stopPct,ACCOUNT-RESERVE);if(notional<5.05)return null;const score=8+10+14+14+18+10+10+4+(setup.type==='BREAKOUT_RETEST'?2:0);return {lane,setup:setup.type,rel,tk,rsi,atr,stopPct,notional,score,swingLow:setup.swingLow}}
function trade(r,p,i,sig){const en=r[i+1]?.o;if(!(en>0))return null;const risk=Math.max(en-sig.swingLow*.998,1.05*sig.atr);if(!(risk>0))return null;const stop=en-risk,target=en+3.2*risk,last=Math.min(r.length-1,i+1+HOLD_BARS);let ex=r[last].c,why='TIME',xt=r[last].t;for(let j=i+1;j<=last;j++){if(r[j].o<=stop){ex=r[j].o;why='GAP_STOP';xt=r[j].t;break}if(r[j].l<=stop){ex=stop;why='STOP';xt=r[j].t;break}if(r[j].h>=target){ex=target;why='TARGET';xt=r[j].t;break}}return {entryT:r[i+1].t,exitT:xt,gross:ex/en-1,notional:sig.notional,lane:sig.lane,setup:sig.setup,reason:why}}
function metrics(t,cost){const rs=t.map(z=>z.gross-cost),gp=rs.filter(x=>x>0).reduce((a,b)=>a+b,0),gl=Math.abs(rs.filter(x=>x<0).reduce((a,b)=>a+b,0));let eq=ACCOUNT,pk=eq,dd=0;for(let i=0;i<t.length;i++){eq+=t[i].notional*rs[i];pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}const profits=t.map((z,i)=>z.notional*rs[i]).filter(x=>x>0).sort((a,b)=>b-a),total=profits.reduce((a,b)=>a+b,0);return {n:rs.length,expectancy:mean(rs),pf:gl?gp/gl:(gp>0?999:0),winRate:rs.length?rs.filter(x=>x>0).length/rs.length:0,maxDD:dd,netPnLUSDT:eq-ACCOUNT,top2ProfitShare:total?profits.slice(0,2).reduce((a,b)=>a+b,0)/total:1}}
function folds(t,cost){if(!t.length)return Array.from({length:5},()=>({n:0,expectancy:0}));const a=t[0].entryT,b=t.at(-1).entryT,w=(b-a||1)/5;return Array.from({length:5},(_,f)=>{const q=t.filter(z=>z.entryT>=a+f*w&&z.entryT<(f===4?b+1:a+(f+1)*w));return {n:q.length,expectancy:q.length?mean(q.map(z=>z.gross-cost)):0}})}

const rows=new Map(),preps=new Map(),h1s=new Map(),p1s=new Map(),h4s=new Map(),p4s=new Map();
for(const s of ['BTCUSDT',...SYMS]){try{const r=await kl15(s);if(r.length>5000){rows.set(s,r);preps.set(s,prep(r));const h1=aggregate(r,60),h4=aggregate(r,240);h1s.set(s,h1);h4s.set(s,h4);p1s.set(s,prep(h1));p4s.set(s,prep(h4));console.error('loaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}
const br=rows.get('BTCUSDT'),b1=h1s.get('BTCUSDT'),b4=h4s.get('BTCUSDT'),bp1=p1s.get('BTCUSDT'),bp4=p4s.get('BTCUSDT');if(!br||!b1||!b4)throw new Error('BTC missing');
const cut=br[0].t+(br.at(-1).t-br[0].t)*.70,holdCut=br[0].t+(br.at(-1).t-br[0].t)*.85;
const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,i]))]));
function run(opt){const tr=[];let occupiedUntil=0;for(let bi=80;bi<br.length-2;bi++){const tm=br[bi].t;if(tm<cut||tm<occupiedUntil)continue;const cand=[];for(const s of SYMS){const r=rows.get(s),p=preps.get(s),i=maps.get(s)?.get(tm);if(i==null||i+2>=r.length)continue;const f=signal(r,p,i,h1s.get(s),p1s.get(s),h4s.get(s),p4s.get(s),b1,bp1,b4,bp4,{...opt,sym:s});if(f)cand.push({s,r,p,i,f})}cand.sort((a,b)=>b.f.score-a.f.score||b.f.rel-a.f.rel);const x=cand[0];if(!x)continue;const z=trade(x.r,x.p,x.i,x.f);if(z){tr.push({sym:x.s,score:x.f.score,rel:x.f.rel,taker:x.f.tk,...z});occupiedUntil=z.exitT}}return tr.sort((a,b)=>a.entryT-b.entryT)}
const baseOpt={bigRel:1.35,smallRel:1.40,bigTaker:.55,smallTaker:.57};
const tr=run(baseOpt),base=metrics(tr,BASE),doubleCost=metrics(tr,STRESS),wf=folds(tr,BASE),positiveFolds=wf.filter(x=>x.n>0&&x.expectancy>0).length,holdout=metrics(tr.filter(x=>x.entryT>=holdCut),BASE);
const neighbors=[];for(const dr of [-.10,0,.10])for(const dt of [-.01,0,.01]){const o={bigRel:baseOpt.bigRel+dr,smallRel:baseOpt.smallRel+dr,bigTaker:baseOpt.bigTaker+dt,smallTaker:baseOpt.smallTaker+dt};const q=run(o),m=metrics(q,BASE);neighbors.push({params:o,n:m.n,expectancy:m.expectancy,pf:m.pf,positive:m.expectancy>0})}
const robustShare=neighbors.filter(x=>x.positive).length/neighbors.length;
const discovery=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&doubleCost.expectancy>0&&positiveFolds>=4&&base.maxDD<=.20;
const paperGate=base.n>=200&&base.pf>=1.20&&holdout.expectancy>0&&base.top2ProfitShare<=.50;
const robustness=robustShare>=.70;
const historicalPass=discovery&&paperGate&&robustness;
const out={generatedAt:new Date().toISOString(),strategy:'HARDENED_EDGE_WORKER_V2_15M_REPLICATION',sourceWorker:'src/edge-worker.js',note:'Historical order-book depth and live spread are unavailable; this is an optimistic proxy, so pass can authorize forward paper only, never live by itself.',oosStart:new Date(cut).toISOString(),finalHoldoutStart:new Date(holdCut).toISOString(),symbols:SYMS,usable:[...rows.keys()],base,doubleCost,folds:wf,positiveFolds,finalHoldout:holdout,robustness:{positiveNeighborShare:robustShare,neighbors},gates:{discovery,paperGate,robustness,historicalPass},verdict:historicalPass?'HISTORICAL_GATE_PASS_FORWARD_PAPER_REQUIRED':'NO_LIVE_APPROVAL',authorization:'FORWARD_PAPER_ONLY',liveTrading:false,validatedStrategyRelease:null,sampleTrades:tr.slice(-12)};
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round26.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
// round26 trigger
