import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const SYMBOLS=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','FILUSDT','ATOMUSDT','APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT'];
const DAYS=1825,OOS=.30,BASE=.003,STRESS=.006;
const G={minN:100,minPF:1.15,minFolds:4,maxDD:.20,minNbr:.70};
const CANDS={XSMOM_90_30:{l1:90,l2:30},XSMOM_180_60:{l1:180,l2:60},XSMOM_60_20:{l1:60,l2:20}};
async function get(p){let last;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();last=`${b}:${r.status}`}catch(e){last=e.message}}throw new Error(last||p)}
async function klines(s){const out=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=1d&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)out.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return out.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
function ema(v,p){const out=new Array(v.length).fill(NaN);if(v.length<p)return out;let m=mean(v.slice(0,p));out[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);out[i]=m}return out}
function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function maxDD(rets){let eq=1,pk=1,d=0;for(const x of rets){eq*=1+x;pk=Math.max(pk,eq);d=Math.max(d,1-eq/pk)}return d}
function met(tr,cost){const r=tr.map(x=>x.gross-cost),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));const ps=[...w].sort((a,b)=>b-a);return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:maxDD(r),top2Share:gp?ps.slice(0,2).reduce((s,x)=>s+x,0)/gp:0}}
function folds(tr,cost,start,end){const w=(end-start)/5,o=[];for(let f=0;f<5;f++){const a=start+f*w,b=f===4?end+1:start+(f+1)*w,t=tr.filter(x=>x.t>=a&&x.t<b);o.push({n:t.length,expectancy:mean(t.map(x=>x.gross-cost))})}return o}
const rows=new Map();for(const s of SYMBOLS){try{const r=await klines(s);if(r.length>400){rows.set(s,r);console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}
const btc=rows.get('BTCUSDT');if(!btc)throw new Error('BTC missing');const btcIndex=new Map(btc.map((x,i)=>[x.t,i])),btc50=ema(btc.map(x=>x.c),50),btc200=ema(btc.map(x=>x.c),200);
const prepared=new Map();for(const [s,r] of rows){const c=r.map(x=>x.c),e100=ema(c,100),ret1=c.map((x,i)=>i?x/c[i-1]-1:NaN);prepared.set(s,{r,c,e100,ret1,index:new Map(r.map((x,i)=>[x.t,i]))})}
function run(cfg,reb=7,w1=.65){const w2=1-w1,tr=[];const times=btc.map(x=>x.t);for(let ti=200;ti<times.length-reb-1;ti+=reb){const t=times[ti],bi=btcIndex.get(t);if(!(btc[bi].c>btc200[bi]&&btc50[bi]>btc200[bi]))continue;const picks=[];for(const [s,p] of prepared){if(s==='BTCUSDT')continue;const i=p.index.get(t);if(i==null||i<Math.max(cfg.l1,100,20))continue;const r1=p.c[i]/p.c[i-cfg.l1]-1,r2=p.c[i]/p.c[i-cfg.l2]-1,vol=sd(p.ret1.slice(i-20,i).filter(Number.isFinite))*Math.sqrt(20),score=w1*r1+w2*r2-.20*vol;if(p.c[i]>p.e100[i]&&score>0)picks.push({s,i,score})}picks.sort((a,b)=>b.score-a.score);for(const pck of picks.slice(0,2)){const p=prepared.get(pck.s),entryI=pck.i+1,exitT=times[Math.min(times.length-1,ti+reb+1)],exitI=p.index.get(exitT);if(exitI==null||entryI>=p.r.length||exitI>=p.r.length)continue;const en=p.r[entryI].o,ex=p.r[exitI].o;if(en>0&&ex>0)tr.push({t:p.r[exitI].t,sym:pck.s,gross:ex/en-1})}}return tr.sort((a,b)=>a.t-b.t)}
const minT=Math.min(...[...rows.values()].map(r=>r[0].t)),maxT=Math.max(...[...rows.values()].map(r=>r.at(-1).t)),cut=minT+(maxT-minT)*(1-OOS);
const res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round5.json',cutoff:new Date(cut).toISOString(),reports:{}};
for(const [name,cfg] of Object.entries(CANDS)){const all=run(cfg),oos=all.filter(x=>x.t>=cut),base=met(oos,BASE),stress=met(oos,STRESS),fs=folds(oos,BASE,cut,maxT),pfolds=fs.filter(x=>x.n>0&&x.expectancy>0).length;let pos=0,n=0,nbr=[];for(const reb of [5,7,10])for(const w1 of [.55,.65,.75]){const t=run(cfg,reb,w1).filter(x=>x.t>=cut),m=met(t,BASE),ok=m.expectancy>0&&m.pf>1;pos+=ok?1:0;n++;nbr.push({rebalanceDays:reb,w1,n:m.n,expectancy:m.expectancy,pf:m.pf,ok})}const frac=pos/n,pass=base.n>=G.minN&&base.pf>=G.minPF&&base.expectancy>0&&stress.expectancy>0&&pfolds>=G.minFolds&&base.maxDD<=G.maxDD&&frac>=G.minNbr;res.reports[name]={allTrades:all.length,oosBase:base,oosDoubleCost:stress,folds:fs,positiveFolds:pfolds,neighborFraction:frac,neighbors:nbr,discoveryPass:pass}}
res.discoveryWinners=Object.entries(res.reports).filter(([,v])=>v.discoveryPass).map(([k])=>k);res.verdict=res.discoveryWinners.length?'PROCEED_TO_UNTOUCHED_SYMBOL_HOLDOUT':'NO_STRATEGY_APPROVED';await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round5-discovery.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
