import fs from 'node:fs/promises';
const BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://data-api.binance.vision'];
const SEEN=new Set(['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','NEARUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','FILUSDT','ATOMUSDT','APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT']);
const HOLD=['XLMUSDT','HBARUSDT','ICPUSDT','ALGOUSDT','VETUSDT','THETAUSDT','RUNEUSDT','GRTUSDT'];const HOLDSET=new Set(HOLD);
const BADBASE=new Set(['USDC','FDUSD','TUSD','USDP','DAI','EUR','AEUR','TRY','BRL','BIDR','IDRT','UAH','NGN','RUB','GBP','AUD','BUSD','USD1','RLUSD','XAUT','PAXG','WBTC','WETH']);
const DAYS=1825,OOS=.30,BASE=.0036,STRESS=.0072,ACCOUNT=20.12,ORDER=7,RESERVE=2,MAXRISK=.20;
const CFG={mom:180,reb:42,k:2,min:.10,stop:.0275,target:.12,hold:42};
async function get(p){let e;for(const b of BASES){try{const r=await fetch(b+p,{signal:AbortSignal.timeout(25000)});if(r.ok)return r.json();e=`${b}:${r.status}`}catch(x){e=x.message}}throw new Error(e||p)}
async function pick(){const ex=await get('/api/v3/exchangeInfo'),tk=await get('/api/v3/ticker/24hr'),m=new Map(ex.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed).map(x=>[x.symbol,x]));return tk.filter(x=>m.has(x.symbol)&&!SEEN.has(x.symbol)&&!HOLDSET.has(x.symbol)).filter(x=>{const b=m.get(x.symbol).baseAsset;return !BADBASE.has(b)&&!/(UP|DOWN|BULL|BEAR)$/.test(b)}).map(x=>({s:x.symbol,q:+x.quoteVolume})).filter(x=>Number.isFinite(x.q)&&x.q>0).sort((a,b)=>b.q-a.q).slice(0,50).map(x=>x.s)}
async function kl(s){const o=[];let cur=Date.now()-DAYS*864e5,now=Date.now();while(cur<now){const p=await get(`/api/v3/klines?symbol=${s}&interval=4h&limit=1000&startTime=${cur}`);if(!p.length)break;for(const k of p)o.push({t:+k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],ct:+k[6]});const n=+p.at(-1)[6]+1;if(n<=cur)break;cur=n;if(p.length<1000)break}return o.filter(x=>x.ct<now)}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;function ema(v,p){const o=new Array(v.length).fill(NaN);if(v.length<p)return o;let m=mean(v.slice(0,p));o[p-1]=m;const k=2/(p+1);for(let i=p;i<v.length;i++){m=v[i]*k+m*(1-k);o[i]=m}return o}
function exitTrade(r,ei){const en=r[ei].o,st=en*(1-CFG.stop),tg=en*(1+CFG.target);let ex=r[Math.min(ei+CFG.hold,r.length-1)].c,xt=r[Math.min(ei+CFG.hold,r.length-1)].t,reason='TIME';for(let j=ei;j<Math.min(r.length,ei+CFG.hold+1);j++){if(r[j].l<=st){ex=st;xt=r[j].t;reason='STOP';break}if(r[j].h>=tg){ex=tg;xt=r[j].t;reason='TARGET';break}}return {entryT:r[ei].t,exitT:xt,gross:ex/en-1,reason}}
function sim(rows,symbols){const maps=new Map([...rows].map(([s,r])=>[s,new Map(r.map((x,i)=>[x.t,{...x,i}]))]));const br=rows.get('BTCUSDT'),bm=maps.get('BTCUSDT'),be=ema(br.map(x=>x.c),600),ts=br.map(x=>x.t),out=[];for(let ti=600;ti<ts.length;ti++){if(ti%CFG.reb!==0)continue;const t=ts[ti],b=bm.get(t);if(!b||!(b.c>be[b.i]))continue;const b30=b.i>=180?b.c/br[b.i-180].c-1:NaN;if(!(b30>0))continue;const cs=[];for(const s of symbols){const r=rows.get(s);if(!r)continue;const q=maps.get(s).get(t);if(!q||q.i<CFG.mom)continue;const mom=q.c/r[q.i-CFG.mom].c-1;if(mom>=CFG.min)cs.push({s,r,q,mom})}cs.sort((a,b)=>b.mom-a.mom);for(const x of cs.slice(0,CFG.k)){const ei=x.q.i+1;if(ei<x.r.length)out.push({sym:x.s,momentum:x.mom,...exitTrade(x.r,ei)})}}return out.sort((a,b)=>a.entryT-b.entryT)}
function dd(rs){let eq=ACCOUNT,pk=ACCOUNT,m=0;for(const x of rs){eq=Math.max(0,eq+ORDER*x);pk=Math.max(pk,eq);m=Math.max(m,1-eq/pk);if(eq<=0)return 1}return Math.min(1,m)}function met(t,c){const r=t.map(x=>x.gross-c),w=r.filter(x=>x>0),l=r.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(l.reduce((s,x)=>s+x,0));return {n:r.length,expectancy:mean(r),pf:gl?gp/gl:(gp>0?999:0),winRate:r.length?w.length/r.length:0,maxDD:dd(r)}}
function folds(t,c,a,b){const w=(b-a)/5,o=[];for(let f=0;f<5;f++){const lo=a+f*w,hi=f===4?b+1:a+(f+1)*w,x=t.filter(z=>z.entryT>=lo&&z.entryT<hi);o.push({n:x.length,expectancy:mean(x.map(z=>z.gross-c))})}return o}
function top2(t,c=BASE){const p=t.map(x=>Math.max(0,x.gross-c)).sort((a,b)=>b-a),tot=p.reduce((s,x)=>s+x,0);return tot?((p[0]||0)+(p[1]||0))/tot:1}
function capital(t,maxPositions=1){let eq=ACCOUNT,peak=eq,maxDD=0,ruined=false,accepted=0,rejected=0;const open=[];for(const tr of [...t].sort((a,b)=>a.entryT-b.entryT)){for(let i=open.length-1;i>=0;i--)if(open[i]<=tr.entryT)open.splice(i,1);if(open.length>=maxPositions||eq<ORDER+RESERVE){rejected++;continue}const priceRisk=ORDER*CFG.stop;if(priceRisk>MAXRISK){rejected++;continue}const pnl=ORDER*(tr.gross-BASE);eq=Math.max(0,eq+pnl);accepted++;open.push(tr.exitT);peak=Math.max(peak,eq);maxDD=Math.max(maxDD,peak?1-eq/peak:1);if(eq<=0){ruined=true;break}}return {endingEquity:eq,totalPnl:eq-ACCOUNT,accepted,rejected,maxDD:Math.min(1,maxDD),ruined,maxPositions}}
async function load(symbols){const rows=new Map();for(const s of ['BTCUSDT',...symbols]){try{const r=await kl(s);if(r.length>600){rows.set(s,r);console.error('downloaded',s,r.length)}}catch(e){console.error('skip',s,e.message)}}return rows}
const symbols=await pick();console.error('selected',symbols.join(','));const rows=await load(symbols),usable=symbols.filter(s=>rows.has(s));const br=rows.get('BTCUSDT'),end=br.at(-1).t,start=br[0].t,cut=start+(end-start)*(1-OOS),all=sim(rows,usable),oos=all.filter(x=>x.entryT>=cut),base=met(oos,BASE),stress=met(oos,STRESS),wf=folds(oos,BASE,cut,end),pfolds=wf.filter(x=>x.n>0&&x.expectancy>0).length,repPass=base.n>=100&&base.pf>=1.15&&base.expectancy>0&&stress.expectancy>0&&pfolds>=4&&base.maxDD<=.20;
const res={generatedAt:new Date().toISOString(),status:'RESEARCH_ONLY',protocol:'validation/evidence-gate-round12.json',selectedSymbols:symbols,usableSymbols:usable,cutoff:new Date(cut).toISOString(),replication:{allTrades:all.length,oosBase:base,oosDoubleCost:stress,folds:wf,positiveFolds:pfolds,topTwoProfitShare:top2(oos),pass:repPass},finalHoldout:null,capital:null,verdict:repPass?'PROCEED_TO_FINAL_HOLDOUT':'REPLICATION_FAILED'};
if(repPass){const hr=await load(HOLD),ht=sim(hr,HOLD),hm=met(ht,BASE),hs=met(ht,STRESS),hpass=hm.n>0&&hm.expectancy>0&&hm.pf>=1.15&&hs.expectancy>0;res.finalHoldout={trades:ht.length,base:hm,doubleCost:hs,topTwoProfitShare:top2(ht),pass:hpass};if(hpass){const pooledN=48+base.n+hm.n;const paperPass=pooledN>=200&&base.pf>=1.20&&hm.expectancy>0&&top2(oos)<=.50&&top2(ht)<=.50;res.capital={onePosition:capital([...oos,...ht],1),twoPositions:capital([...oos,...ht],2)};res.verdict=paperPass?'PAPER_CANDIDATE_APPROVED':'PAPER_GATE_FAILED'}else res.verdict='FINAL_HOLDOUT_FAILED'}
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/round12-replication.json',JSON.stringify(res,null,2));console.log(JSON.stringify(res,null,2));
