import baseWorker, { SignalState } from "./edge-worker.js";
export { SignalState };

const SIGNAL_TTL_SEC=10*60, PREPARE_TTL_SEC=5*60, BALANCE_CHECK_SEC=5*60, MIN_ORDER_USDT=5, MAX_BALANCE_FRACTION=.80, MAX_RISK_USDT=.20;
const BINANCE_API_BASES=["https://api.binance.com","https://api-gcp.binance.com","https://api1.binance.com","https://api2.binance.com","https://api3.binance.com","https://api4.binance.com"];
function creds(env){return{key:env.BINANCE_API_KEY||env.BINANCE_KEY||env.BINANCE_APIKEY||"",secret:env.BINANCE_API_SECRET||env.BINANCE_SECRET||env.BINANCE_SECRET_KEY||""};}
function stateStub(env){const id=env.STATE_COORDINATOR.idFromName("global");return env.STATE_COORDINATOR.get(id);}
async function getState(env,key){const r=await stateStub(env).fetch(`https://state/get?key=${encodeURIComponent(key)}`);return r.ok?await r.json():null;}
async function putState(env,key,value,ttl){await stateStub(env).fetch(`https://state/put?key=${encodeURIComponent(key)}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({value,expiresAt:Date.now()+ttl*1000})});}
async function tg(env,method,payload){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({ok:false}));if(!r.ok||j.ok===false)throw new Error(`Telegram ${method} failed`);return j;}
function fmt(v){return Number(v||0).toLocaleString("en-US",{useGrouping:false,maximumFractionDigits:8});}
function compactId(p){const raw=`${p.symbol}:${p.openedAt||p.createdAt||Date.now()}:${p.entry}`;let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36);}
async function hmacHex(secret,text){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(text));return[...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function sanitize(text,status){try{const j=JSON.parse(text||"{}");return`${j.code||status}: ${j.msg||"Binance request failed"}`}catch{return`HTTP ${status}`}}
async function publicBinance(path){for(const base of ["https://data-api.binance.vision",...BINANCE_API_BASES])try{const r=await fetch(base+path),t=await r.text();if(r.ok)return JSON.parse(t||"{}")}catch{}throw new Error("BINANCE_PUBLIC_UNAVAILABLE");}
async function signedBinanceDirect(env,method,path,params={}){const c=creds(env);if(!c.key||!c.secret)throw new Error(`BINANCE_KEYS_MISSING:key=${Boolean(c.key)},secret=${Boolean(c.secret)}`);const all={...params,recvWindow:5000,timestamp:Date.now()},qs=new URLSearchParams(Object.entries(all).map(([k,v])=>[k,String(v)])).toString(),signature=await hmacHex(c.secret,qs);let last="BINANCE_UNAVAILABLE";for(const base of BINANCE_API_BASES)try{const r=await fetch(`${base}${path}?${qs}&signature=${signature}`,{method,headers:{"X-MBX-APIKEY":c.key,"content-type":"application/x-www-form-urlencoded"}}),t=await r.text();if(r.ok){const d=JSON.parse(t||"{}");if(!(Number(d.code)<0))return d;}last=sanitize(t,r.status)}catch(e){last=String(e?.message||e)}throw new Error(last);}
function decimals(s){s=String(s);if(s.includes("e-"))return Number(s.split("e-")[1]);return(s.split(".")[1]||"").replace(/0+$/,"").length;}
function floorTo(v,s){return!s||s<=0?v:Number((Math.floor((v+1e-12)/s)*s).toFixed(decimals(s)));}
function roundTo(v,t){return!t||t<=0?v:Number((Math.round(v/t)*t).toFixed(decimals(t)));}
function dynamicQuote(f,e,s){const p=(e-s)/e;if(!(p>0))throw new Error("INVALID_STOP_DISTANCE");return Math.floor(Math.min(MAX_RISK_USDT/p,f*MAX_BALANCE_FRACTION)*100)/100;}
async function getBalanceDirect(env){const a=await signedBinanceDirect(env,"GET","/api/v3/account",{}),get=x=>{const b=(a.balances||[]).find(y=>y.asset===x)||{},free=Number(b.free||0),locked=Number(b.locked||0);return{free,locked,total:free+locked}};return{ok:true,status:"ACCOUNT_BALANCE_OK",canTrade:Boolean(a.canTrade),usdt:get("USDT"),sol:get("SOL"),source:"CLOUDFLARE_DIRECT_BINANCE",at:Date.now()};}
async function refreshBalance(env){try{const b=await getBalanceDirect(env);await putState(env,"binance:balance:last",b,7200);return b}catch(e){await putState(env,"binance:balance:error",{at:Date.now(),error:String(e?.message||e)},1800);return null}}
async function executeDirect(env,s){const entry=Number(s.entry),stopRef=Number(s.stop),targetRef=Number(s.target),symbol=String(s.symbol||"").toUpperCase();const info=await publicBinance(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`),m=info.symbols?.[0];if(!m||m.status!=="TRADING"||!m.isSpotTradingAllowed)throw new Error("PAIR_NOT_TRADABLE_SPOT");const a=await signedBinanceDirect(env,"GET","/api/v3/account",{}),free=Number((a.balances||[]).find(b=>b.asset==="USDT")?.free||0),safe=dynamicQuote(free,entry,stopRef),quote=Math.floor(Math.min(Number(s.confirmedQuoteUSDT||s.recommendedUSDT||safe),safe,free*MAX_BALANCE_FRACTION)*100)/100;if(quote<MIN_ORDER_USDT)throw new Error("SIZE_BELOW_MINIMUM");const buy=await signedBinanceDirect(env,"POST","/api/v3/order",{symbol,side:"BUY",type:"MARKET",quoteOrderQty:quote.toFixed(2),newOrderRespType:"FULL"}),qty=Number(buy.executedQty||0),spent=Number(buy.cummulativeQuoteQty||0),avg=spent/qty,lot=m.filters.find(x=>x.filterType==="LOT_SIZE"),pf=m.filters.find(x=>x.filterType==="PRICE_FILTER"),step=Number(lot?.stepSize||".00000001"),tick=Number(pf?.tickSize||".00000001"),stop=roundTo(avg*(stopRef/entry),tick),tp=roundTo(avg*(targetRef/entry),tick),stopLimit=roundTo(stop*.997,tick),sellQty=floorTo(qty*.999,step);let oco=null,ocoError=null;try{oco=await signedBinanceDirect(env,"POST","/api/v3/orderList/oco",{symbol,side:"SELL",quantity:sellQty,aboveType:"LIMIT_MAKER",abovePrice:tp,belowType:"STOP_LOSS_LIMIT",belowStopPrice:stop,belowPrice:stopLimit,belowTimeInForce:"GTC"})}catch(e){ocoError=String(e?.message||e)}return{quoteUSDT:spent,executedQty:qty,avg,tp,stop,ocoPlaced:Boolean(oco),ocoError};}
async function sendPromptForActive(env){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return;const active=(await getState(env,"paper:active"))||[],b=(await getState(env,"binance:balance:last"))||await refreshBalance(env),free=Number(b?.usdt?.free||0);for(const p of active){const id=compactId(p);if(await getState(env,`buy-prompt:${id}`))continue;const s={id,symbol:p.symbol,entry:Number(p.entry),stop:Number(p.stop),target:Number(p.target),strategy:p.strategy||"Scanner",score:p.score||null,createdAt:Date.now(),expiresAt:Date.now()+SIGNAL_TTL_SEC*1000};if(!(s.stop<s.entry&&s.target>s.entry))continue;const rec=free>0?dynamicQuote(free,s.entry,s.stop):0;s.recommendedUSDT=rec;await putState(env,`live-signal:${id}`,s,SIGNAL_TTL_SEC);if(rec>=MIN_ORDER_USDT)await tg(env,"sendMessage",{chat_id:String(env.TELEGRAM_CHAT_ID),text:`🚨 ${p.symbol}\n💵 ${fmt(rec)} USDT\n💲 Entry ${fmt(s.entry)}\n🎯 TP ${fmt(s.target)}\n🛑 SL ${fmt(s.stop)}\n⭐ Score ${s.score??"—"}/100`,reply_markup:{inline_keyboard:[[{text:`🧾 PREPARE ${fmt(rec)} USDT`,callback_data:`PREP:${id}`}]]}});await putState(env,`buy-prompt:${id}`,{sentAt:Date.now()},SIGNAL_TTL_SEC)}}
async function handleTelegramWebhook(request,env){const u=await request.json().catch(()=>null),q=u?.callback_query;if(!q)return new Response("ok");if(String(q.message?.chat?.id||"")!==String(env.TELEGRAM_CHAT_ID||""))return new Response("ok");const [action,id]=String(q.data||"").split(":");const s=await getState(env,`live-signal:${id}`);if(action==="PREP"&&s){const b=await refreshBalance(env),free=Number(b?.usdt?.free||0),rec=dynamicQuote(free,Number(s.entry),Number(s.stop)),p={...s,confirmedQuoteUSDT:rec,prepareExpiresAt:Date.now()+PREPARE_TTL_SEC*1000};await putState(env,`prepared:${id}`,p,PREPARE_TTL_SEC);await tg(env,"answerCallbackQuery",{callback_query_id:q.id,text:"Trade prepared — no purchase yet"});await tg(env,"sendMessage",{chat_id:String(env.TELEGRAM_CHAT_ID),text:`🧾 TRADE READY — ${p.symbol}\n💵 ${fmt(rec)} USDT\n💲 Entry ${fmt(p.entry)}\n🎯 TP ${fmt(p.target)}\n🛑 SL ${fmt(p.stop)}\n\n⚠️ CONFIRM BUY ينفذ شراء حقيقي.`,reply_markup:{inline_keyboard:[[{text:`✅ CONFIRM BUY ${fmt(rec)} USDT`,callback_data:`CONFIRM:${id}`}],[{text:"❌ CANCEL",callback_data:`CANCEL:${id}`}]]}});return new Response("ok")}if(action==="CANCEL"){await putState(env,`prepared:${id}`,null,1);await tg(env,"answerCallbackQuery",{callback_query_id:q.id,text:"Cancelled"});return new Response("ok")}if(action==="CONFIRM"){const p=await getState(env,`prepared:${id}`);if(!p||Date.now()>Number(p.prepareExpiresAt||0)){await tg(env,"answerCallbackQuery",{callback_query_id:q.id,text:"Expired",show_alert:true});return new Response("ok")}await tg(env,"answerCallbackQuery",{callback_query_id:q.id,text:"Executing confirmed Spot BUY…"});try{const r=await executeDirect(env,p);await tg(env,"sendMessage",{chat_id:String(env.TELEGRAM_CHAT_ID),text:`✅ BUY تم — ${p.symbol}\n💵 ${fmt(r.quoteUSDT)} USDT\n💲 ${fmt(r.avg)}\n${r.ocoPlaced?`✅ TP ${fmt(r.tp)} | SL ${fmt(r.stop)}`:`⚠️ OCO failed: ${r.ocoError}`}`})}catch(e){await tg(env,"sendMessage",{chat_id:String(env.TELEGRAM_CHAT_ID),text:`❌ BUY failed: ${String(e?.message||e).slice(0,250)}`})}return new Response("ok")}return new Response("ok")}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/telegram-webhook"&&request.method==="POST")return handleTelegramWebhook(request,env);if(url.pathname==="/runtime-check"){const c=creds(env);return Response.json({ok:true,hasApiKey:Boolean(c.key),hasApiSecret:Boolean(c.secret),keyAlias:env.BINANCE_API_KEY?"BINANCE_API_KEY":env.BINANCE_KEY?"BINANCE_KEY":env.BINANCE_APIKEY?"BINANCE_APIKEY":null,secretAlias:env.BINANCE_API_SECRET?"BINANCE_API_SECRET":env.BINANCE_SECRET?"BINANCE_SECRET":env.BINANCE_SECRET_KEY?"BINANCE_SECRET_KEY":null,telegramConfigured:Boolean(env.TELEGRAM_BOT_TOKEN&&env.TELEGRAM_CHAT_ID),noSecretValuesExposed:true})}if(url.pathname==="/balance-refresh"){const balance=await refreshBalance(env),error=balance?null:await getState(env,"binance:balance:error");return Response.json({ok:Boolean(balance),balance,error,autoBuy:false})}return baseWorker.fetch(request,env,ctx)},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{if(baseWorker.scheduled)await baseWorker.scheduled(event,env,ctx);await refreshBalance(env);await sendPromptForActive(env)})())}};